twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        global: '@App\globalVar'
        organizationM: '@App\Model\OrganizationM'
        activityM: '@App\Model\ActivityM'
        userM: '@App\Model\UserM'
        departmentM: '@App\Model\DepartmentM'
        freeAccessRoutes: '/fr'
        userRepo: '@App\Repository\UserRepository'
