<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajout de toutes les entity et de champs basiques (sans les relations)
 */
final class AjoutEntity extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT AUTO_INCREMENT NOT NULL, act_complete TINYINT(1) NOT NULL, act_master_usr_id INT NOT NULL, act_magnitude INT NOT NULL, act_simplified TINYINT(1) NOT NULL, act_name VARCHAR(255) NOT NULL, act_visibility VARCHAR(255) NOT NULL, act_start_date DATETIME NOT NULL, act_end_date DATETIME NOT NULL, act_objectives VARCHAR(255) NOT NULL, act_status INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity_user (id INT AUTO_INCREMENT NOT NULL, user_usr_id INT NOT NULL, a_u_status INT NOT NULL, a_u_aw_result DOUBLE PRECISION DEFAULT NULL, a_u_ae_result DOUBLE PRECISION DEFAULT NULL, a_u_re_result DOUBLE PRECISION DEFAULT NULL, a_u_e_dev DOUBLE PRECISION DEFAULT NULL, a_u_w_devratio DOUBLE PRECISION DEFAULT NULL, a_u_e_devratio DOUBLE PRECISION DEFAULT NULL, a_u_leader TINYINT(1) NOT NULL, a_u_type INT NOT NULL, a_u_m_weight DOUBLE PRECISION NOT NULL, a_u_precomment VARCHAR(10) DEFAULT NULL, a_u_ivp_bonus DOUBLE PRECISION NOT NULL, a_u_ivp_penalty DOUBLE PRECISION NOT NULL, a_u_of_bonys DOUBLE PRECISION NOT NULL, a_u_of_penalty DOUBLE PRECISION NOT NULL, a_u_mailed TINYINT(1) DEFAULT NULL, a_u_created_by INT DEFAULT NULL, a_u_inserted DATETIME DEFAULT NULL, a_u_confirmed DATETIME DEFAULT NULL, a_u_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE answer (id INT AUTO_INCREMENT NOT NULL, asw_text VARCHAR(255) NOT NULL, asw_created_by INT NOT NULL, asw_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appreciation (id INT AUTO_INCREMENT NOT NULL, apt_value DOUBLE PRECISION NOT NULL, apt_comment VARCHAR(255) NOT NULL, apt_created_by INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, cit_abbr VARCHAR(255) NOT NULL, cit_fullname VARCHAR(255) NOT NULL, cit_name VARCHAR(255) NOT NULL, cit_created_by INT DEFAULT NULL, cit_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, clicommname VARCHAR(255) NOT NULL, cli_type VARCHAR(255) NOT NULL, cli_logo VARCHAR(255) NOT NULL, cli_email VARCHAR(255) DEFAULT NULL, cli_created_by INT NOT NULL, cli_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, con_locale VARCHAR(255) NOT NULL, con_type VARCHAR(255) NOT NULL, con_sent TINYINT(1) NOT NULL, con_fullname VARCHAR(255) NOT NULL, con_compagny VARCHAR(255) NOT NULL, con_adress VARCHAR(255) NOT NULL, con_zip_code INT NOT NULL, con_city VARCHAR(255) NOT NULL, con_country VARCHAR(255) NOT NULL, con_position VARCHAR(255) NOT NULL, con_email VARCHAR(255) NOT NULL, con_message VARCHAR(255) NOT NULL, con_newsletter TINYINT(1) NOT NULL, con_doc TINYINT(1) NOT NULL, con_mdate DATETIME NOT NULL, con_mtime DATETIME NOT NULL, con_inserted DATETIME NOT NULL, con_confirmed DATETIME NOT NULL, con_created_by INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country (id INT AUTO_INCREMENT NOT NULL, cou_abbr VARCHAR(255) NOT NULL, cou_fullname VARCHAR(255) NOT NULL, cou_name VARCHAR(255) NOT NULL, cou_created_by INT DEFAULT NULL, cou_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterion (id INT AUTO_INCREMENT NOT NULL, cri_complete TINYINT(1) NOT NULL, cri_type INT NOT NULL, cri_name VARCHAR(255) NOT NULL, cri_weight DOUBLE PRECISION NOT NULL, cri_force_comment_compare TINYINT(1) NOT NULL, cri_force_comment_value DOUBLE PRECISION DEFAULT NULL, cri_force_comment_sign VARCHAR(255) DEFAULT NULL, cri_lowerbound DOUBLE PRECISION DEFAULT NULL, cri_upperbound DOUBLE PRECISION DEFAULT NULL, cri_step DOUBLE PRECISION DEFAULT NULL, cri_grade_type INT NOT NULL, cri_avg_ae_res DOUBLE PRECISION NOT NULL, cri_avg_rw_res VARCHAR(255) NOT NULL, cri_avg_re_res DOUBLE PRECISION NOT NULL, cri_max_w_dev DOUBLE PRECISION NOT NULL, cri_max_e_dev DOUBLE PRECISION NOT NULL, cri_avg_w_dev DOUBLE PRECISION NOT NULL, cri_avg_e_dev DOUBLE PRECISION NOT NULL, cri_w_inertia DOUBLE PRECISION NOT NULL, cri_e_inertia DOUBLE PRECISION NOT NULL, cri_max_w_inertia DOUBLE PRECISION NOT NULL, cri_max_e_inertia DOUBLE PRECISION NOT NULL, cri_w_distratio DOUBLE PRECISION NOT NULL, cri_comment VARCHAR(255) NOT NULL, cri_created_by INT DEFAULT NULL, cri_inserted DATETIME DEFAULT NULL, cri_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterion_group (id INT AUTO_INCREMENT NOT NULL, cgp_created_by INT NOT NULL, cgp_inserted DATETIME NOT NULL, cgp_name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterion_name (id INT AUTO_INCREMENT NOT NULL, cna_type INT NOT NULL, cna_name VARCHAR(255) NOT NULL, can_unit VARCHAR(255) NOT NULL, can_created_by INT NOT NULL, can_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE decision (id INT AUTO_INCREMENT NOT NULL, dec_type INT NOT NULL, req_anon INT NOT NULL, dec_anon TINYINT(1) DEFAULT NULL, val_usr_id INT NOT NULL, dec_result INT NOT NULL, dec_created_by INT NOT NULL, dec_inserted DATETIME NOT NULL, dec_decided DATETIME NOT NULL, dec_validated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE departement (id INT AUTO_INCREMENT NOT NULL, dpt_name VARCHAR(45) NOT NULL, dpt_created_by INT NOT NULL, dpt_inserted DATETIME NOT NULL, dpt_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE external_user (id INT AUTO_INCREMENT NOT NULL, ext_fisrtname VARCHAR(255) NOT NULL, ext_lastname VARCHAR(255) NOT NULL, ext_email VARCHAR(255) DEFAULT NULL, ext_position_name VARCHAR(255) NOT NULL, ext_weight_value DOUBLE PRECISION NOT NULL, ext_owner TINYINT(1) NOT NULL, ext_created_by INT NOT NULL, ext_inserted DATETIME NOT NULL, ext_last_connected DATETIME DEFAULT NULL, ext_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE generated_image (id INT AUTO_INCREMENT NOT NULL, gim_all INT NOT NULL, gim_type INT NOT NULL, gim_tid INT DEFAULT NULL, gim_uid INT DEFAULT NULL, gim_aid INT DEFAULT NULL, gim_ov TINYINT(1) NOT NULL, gim_sid INT DEFAULT NULL, gim_role INT DEFAULT NULL, gim_created_by INT DEFAULT NULL, gim_val VARCHAR(255) NOT NULL, gim_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gpw (id INT AUTO_INCREMENT NOT NULL, gpw_pid VARCHAR(255) NOT NULL, gpw_firm VARCHAR(255) NOT NULL, gpw_sector VARCHAR(255) NOT NULL, gpw_location VARCHAR(255) NOT NULL, gpw_c_date INT NOT NULL, gpw_nb_workers INT NOT NULL, gpw_website VARCHAR(255) NOT NULL, gpw_gen_mail VARCHAR(255) NOT NULL, gpw_fb VARCHAR(255) NOT NULL, gpw_linked_in VARCHAR(255) NOT NULL, gpw_twitter VARCHAR(255) NOT NULL, gpw_xing VARCHAR(255) NOT NULL, gpw_yt VARCHAR(255) NOT NULL, gpw_insta VARCHAR(255) NOT NULL, gpw_contact_name VARCHAR(255) NOT NULL, gpw_contact_position VARCHAR(255) NOT NULL, gpw_contact_mail VARCHAR(255) NOT NULL, gpw_contact_tel VARCHAR(255) NOT NULL, gpw_values_careers_inspiration VARCHAR(255) NOT NULL, gpw_employee_author VARCHAR(255) NOT NULL, gpw_employee_position VARCHAR(255) NOT NULL, gpw_employee_comment VARCHAR(255) NOT NULL, gpw_boss_author VARCHAR(255) NOT NULL, gpw_boss_division VARCHAR(255) NOT NULL, gpw_boss_comment VARCHAR(255) NOT NULL, gpw_award_year_1 VARCHAR(255) NOT NULL, gpw_award_title_1 VARCHAR(255) NOT NULL, gpw_award_rnk_1 VARCHAR(255) NOT NULL, gpw_award_year_2 VARCHAR(255) NOT NULL, gpw_award_title_2 VARCHAR(255) NOT NULL, gpw_award_rnk_2 VARCHAR(255) NOT NULL, gpw_award_year_3 VARCHAR(255) NOT NULL, gpw_award_title_3 VARCHAR(255) NOT NULL, gpw_award_rnk3 VARCHAR(255) NOT NULL, gpw_survey_text_1 VARCHAR(255) NOT NULL, gpw_survey_res_1 VARCHAR(255) NOT NULL, gpw_survey_text_2 VARCHAR(255) NOT NULL, gpw_survey_res_2 VARCHAR(255) NOT NULL, gpw_survey_text_3 VARCHAR(255) NOT NULL, gpw_survey_res_3 VARCHAR(255) NOT NULL, gpw_survey_text_4 VARCHAR(255) NOT NULL, gpw_survey_res_4 VARCHAR(255) NOT NULL, gpw_survey_text_5 VARCHAR(255) NOT NULL, gpw_survey_res_5 VARCHAR(255) NOT NULL, gpw_survey_text_6 VARCHAR(255) NOT NULL, gpw_survey_res_6 VARCHAR(255) NOT NULL, gpw_survey_text_7 VARCHAR(255) NOT NULL, gpw_survey_res_7 VARCHAR(255) NOT NULL, gpw_created_by INT DEFAULT NULL, gpw_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grade (id INT AUTO_INCREMENT NOT NULL, grd_type INT NOT NULL, grd_graded_usr_id INT NOT NULL, grd_graded_tea_id INT NOT NULL, grd_value DOUBLE PRECISION NOT NULL, grd_comment VARCHAR(255) DEFAULT NULL, grd_created_by INT DEFAULT NULL, grd_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE help (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE icon (id INT AUTO_INCREMENT NOT NULL, ico_type VARCHAR(255) NOT NULL, ico_name VARCHAR(255) NOT NULL, ico_unicode VARCHAR(255) NOT NULL, ico_created_by INT DEFAULT NULL, ico_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE insitution_process (id INT AUTO_INCREMENT NOT NULL, inp_name VARCHAR(255) NOT NULL, inp_approvable TINYINT(1) NOT NULL, inp_gradable TINYINT(1) NOT NULL, inp_created_by INT NOT NULL, inp_isnerted DATETIME NOT NULL, inp_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE iprocess_activity_user (id INT AUTO_INCREMENT NOT NULL, a_u_status INT NOT NULL, a_u_leader TINYINT(1) NOT NULL, a_u_type INT NOT NULL, a_u_m_weight DOUBLE PRECISION NOT NULL, a_u_precomment VARCHAR(255) NOT NULL, a_u_created_by INT DEFAULT NULL, a_u_inserted DATETIME DEFAULT NULL, a_u_deleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE iprocess_criterion (id INT AUTO_INCREMENT NOT NULL, crt_type INT NOT NULL, crt_name VARCHAR(255) DEFAULT NULL, crt_weight DOUBLE PRECISION NOT NULL, crt_force_comment_compare TINYINT(1) NOT NULL, crt_force_comment_value DOUBLE PRECISION DEFAULT NULL, crt_force_comment_sign VARCHAR(255) DEFAULT NULL, crt_lower_bound DOUBLE PRECISION DEFAULT NULL, crt_upperbound DOUBLE PRECISION DEFAULT NULL, crt_step DOUBLE PRECISION DEFAULT NULL, crt_comment VARCHAR(255) NOT NULL, crt_created_by INT DEFAULT NULL, crt_inserted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE iprocess_stage (id INT AUTO_INCREMENT NOT NULL, stg_complete TINYINT(1) NOT NULL, stg_name VARCHAR(255) NOT NULL, stg_mod INT NOT NULL, stg_visibility INT NOT NULL, stg_status DOUBLE PRECISION NOT NULL, stg_desc VARCHAR(255) NOT NULL, stg_progress DOUBLE PRECISION NOT NULL, stg_weight DOUBLE PRECISION NOT NULL, stg_dperiod INT NOT NULL, stg_dfrequency VARCHAR(255) NOT NULL, stg_dorigin INT NOT NULL, stg_ffrequency VARCHAR(255) NOT NULL, stg_forigin INT NOT NULL, stg_definite_dates TINYINT(1) NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddate DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_deadline_nb_days INT NOT NULL, stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, stg_created_by INT DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_is_finalized TINYINT(1) NOT NULL, stg_finalized DATETIME NOT NULL, stg_deleted DATETIME NOT NULL, stg_gcompleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lkurl (id INT AUTO_INCREMENT NOT NULL, lk_url_country VARCHAR(10) NOT NULL, lk_url_letter VARCHAR(10) NOT NULL, lk_url_pag_nb VARCHAR(10) NOT NULL, lk_url_value VARCHAR(10) NOT NULL, lk_url_created_by INT NOT NULL, lk_url_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mail (id INT AUTO_INCREMENT NOT NULL, mail_persona VARCHAR(1) NOT NULL, mail_token VARCHAR(255) NOT NULL, mail_read DATETIME NOT NULL, mail_created_by INT NOT NULL, mail_inserted DATETIME NOT NULL, mail_language VARCHAR(3) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE option_name (id INT AUTO_INCREMENT NOT NULL, ona_type INT NOT NULL, ona_name VARCHAR(255) NOT NULL, ona_description VARCHAR(255) NOT NULL, ona_created_by DATETIME NOT NULL, ona_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization (id INT AUTO_INCREMENT NOT NULL, org_legalname VARCHAR(255) NOT NULL, org_commname VARCHAR(255) NOT NULL, org_type VARCHAR(255) NOT NULL, org_is_client TINYINT(1) NOT NULL, org_oth_language VARCHAR(255) NOT NULL, org_weight_type VARCHAR(255) NOT NULL, org_logo VARCHAR(255) DEFAULT NULL, org_created_by INT NOT NULL, org_inserted DATETIME NOT NULL, org_validated DATETIME NOT NULL, org_expired DATETIME NOT NULL, org_testing_reminder_sent TINYINT(1) NOT NULL, org_deleted DATETIME DEFAULT NULL, org_routine_pstatus DATETIME DEFAULT NULL, org_routine_greminders DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_user_option (id INT AUTO_INCREMENT NOT NULL, opt_bool_value TINYINT(1) NOT NULL, opt_int_value DOUBLE PRECISION NOT NULL, opt_int_value_2 DOUBLE PRECISION NOT NULL, opt_float_value DOUBLE PRECISION NOT NULL, pot_string_value VARCHAR(255) NOT NULL, opt_enabled TINYINT(1) NOT NULL, opt_created_by INT DEFAULT NULL, opt_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE otpuser (id INT AUTO_INCREMENT NOT NULL, otp_type VARCHAR(1) NOT NULL, otp_fullname VARCHAR(255) NOT NULL, otp_tipe VARCHAR(255) NOT NULL, otp_email VARCHAR(255) NOT NULL, otp_created_by INT DEFAULT NULL, otp_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE position (id INT AUTO_INCREMENT NOT NULL, pos_name VARCHAR(255) NOT NULL, pos_weight_ini DOUBLE PRECISION NOT NULL, pos_weight_1y DOUBLE PRECISION NOT NULL, pos_weight_2y DOUBLE PRECISION NOT NULL, pos_weight_3y DOUBLE PRECISION NOT NULL, pos_weight_4y DOUBLE PRECISION NOT NULL, pos_weight_5y DOUBLE PRECISION NOT NULL, pos_created_by INT NOT NULL, pos_inserted DATETIME NOT NULL, pos_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE process (id INT AUTO_INCREMENT NOT NULL, pro_name VARCHAR(255) NOT NULL, pro_approvable TINYINT(1) NOT NULL, pro_gradable TINYINT(1) NOT NULL, pro_created_by INT NOT NULL, pro_inserted DATETIME NOT NULL, pro_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE process_criterion (id INT AUTO_INCREMENT NOT NULL, crt_type INT NOT NULL, crt_name VARCHAR(255) DEFAULT NULL, crt_weight DOUBLE PRECISION NOT NULL, crt_force_comment_compare TINYINT(1) NOT NULL, crt_force_comment_value DOUBLE PRECISION DEFAULT NULL, crt_force_comment_sign VARCHAR(255) DEFAULT NULL, crt_lowerbound DOUBLE PRECISION DEFAULT NULL, crt_upperbound DOUBLE PRECISION DEFAULT NULL, crt_step DOUBLE PRECISION DEFAULT NULL, crt_comment VARCHAR(255) DEFAULT NULL, crt_created_by INT DEFAULT NULL, crt_inserted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE process_stage (id INT AUTO_INCREMENT NOT NULL, stg_complete TINYINT(1) NOT NULL, stg_name VARCHAR(255) NOT NULL, stg_mode VARCHAR(255) NOT NULL, stg_visibility INT NOT NULL, stg_definite_dates TINYINT(1) NOT NULL, stg_status DOUBLE PRECISION NOT NULL, stg_desc VARCHAR(255) NOT NULL, stg_progress DOUBLE PRECISION NOT NULL, stg_weight VARCHAR(255) NOT NULL, stg_dperiod INT NOT NULL, stg_dfrequency VARCHAR(255) NOT NULL, stg_dorigin INT NOT NULL, stg_fperiod INT NOT NULL, stg_ffrequency VARCHAR(255) NOT NULL, stg_forigin INT NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddated DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_dealine_nb_days INT NOT NULL, stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, stg_created_by INT DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_is_finalized DATETIME NOT NULL, stg_deleted DATETIME NOT NULL, stg_dcompleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking (id INT AUTO_INCREMENT NOT NULL, rnk_dtype VARCHAR(1) NOT NULL, rnk_wtype VARCHAR(1) NOT NULL, rnk_abs_result INT NOT NULL, rnk_rel_result DOUBLE PRECISION NOT NULL, rnk_period INT NOT NULL, rnk_freq INT NOT NULL, rnk_value DOUBLE PRECISION NOT NULL, rnk_series_pop INT NOT NULL, rnk_created_by INT DEFAULT NULL, rnk_inserted DATETIME NOT NULL, rnk_updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking_history (id INT AUTO_INCREMENT NOT NULL, rkh_wtype VARCHAR(1) NOT NULL, rkh_abs_result INT NOT NULL, rkh_rel_result DOUBLE PRECISION NOT NULL, rkh_period INT NOT NULL, rkh_freq INT NOT NULL, rkh_value DOUBLE PRECISION NOT NULL, rkh_series_pop INT NOT NULL, rkh_created_by INT DEFAULT NULL, rkh_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking_team (id INT AUTO_INCREMENT NOT NULL, rkt_dtype VARCHAR(1) NOT NULL, rkt_wtype VARCHAR(1) NOT NULL, rkt_abs_result INT NOT NULL, rkt_rel_result DOUBLE PRECISION NOT NULL, rkt_period INT NOT NULL, rkt_freq INT NOT NULL, rkt_value DOUBLE PRECISION NOT NULL, rkt_series_pop INT NOT NULL, rkt_created_by INT DEFAULT NULL, rkt_inserted DATETIME NOT NULL, rkt_updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking_team_history (id INT AUTO_INCREMENT NOT NULL, rth_dtype VARCHAR(1) NOT NULL, rth_wtype VARCHAR(1) NOT NULL, rth_abs_result INT NOT NULL, rth_rel_result DOUBLE PRECISION NOT NULL, rth_period INT NOT NULL, rth_freq INT NOT NULL, rth_value DOUBLE PRECISION NOT NULL, rth_series_pop INT NOT NULL, rth_creatd_by INT DEFAULT NULL, rth_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE record (id INT AUTO_INCREMENT NOT NULL, rec_table_id INT NOT NULL, rec_property VARCHAR(255) NOT NULL, rec_old VARCHAR(255) NOT NULL, rec_new VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recurring (id INT AUTO_INCREMENT NOT NULL, rct_name VARCHAR(255) NOT NULL, rct_status INT NOT NULL, rct_timeframe VARCHAR(255) NOT NULL, rct_freq INT NOT NULL, rct_gsd_interval INT NOT NULL, rct_gsd_timeframe VARCHAR(255) NOT NULL, rct_ged_interval INT NOT NULL, rct_ged_timeframe VARCHAR(255) NOT NULL, rct_type INT NOT NULL, rct_lowerbound DOUBLE PRECISION NOT NULL, rct_upperbound DOUBLE PRECISION NOT NULL, rct_step DOUBLE PRECISION NOT NULL, rct_opend_end TINYINT(1) NOT NULL, rct_startdate DATETIME NOT NULL, rct_enddate DATETIME NOT NULL, rct_same_part TINYINT(1) NOT NULL, rct_created_by INT DEFAULT NULL, rct_inserted DATETIME NOT NULL, rct_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result (id INT AUTO_INCREMENT NOT NULL, res_type INT DEFAULT NULL, res_war DOUBLE PRECISION DEFAULT NULL, res_ear DOUBLE PRECISION DEFAULT NULL, res_wrr DOUBLE PRECISION DEFAULT NULL, res_err DOUBLE PRECISION DEFAULT NULL, res_wsd DOUBLE PRECISION DEFAULT NULL, res_esd DOUBLE PRECISION DEFAULT NULL, res_wdf DOUBLE PRECISION DEFAULT NULL, res_edr DOUBLE PRECISION DEFAULT NULL, res_wsd_max DOUBLE PRECISION DEFAULT NULL, res_esd_max DOUBLE PRECISION NOT NULL, res_win DOUBLE PRECISION NOT NULL, res_ein DOUBLE PRECISION NOT NULL, res_win_max DOUBLE PRECISION NOT NULL, res_ein_max DOUBLE PRECISION NOT NULL, res_wdr_gen DOUBLE PRECISION NOT NULL, res_res_der_gen DOUBLE PRECISION NOT NULL, res_created_by INT DEFAULT NULL, res_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_project (id INT AUTO_INCREMENT NOT NULL, rsp_type INT DEFAULT NULL, rsp_war DOUBLE PRECISION DEFAULT NULL, rsp_ear DOUBLE PRECISION DEFAULT NULL, rsp_wrr DOUBLE PRECISION DEFAULT NULL, rsp_err DOUBLE PRECISION DEFAULT NULL, rsp_wsd DOUBLE PRECISION DEFAULT NULL, rsp_esd DOUBLE PRECISION DEFAULT NULL, rsp_wdr DOUBLE PRECISION DEFAULT NULL, rsp_edr DOUBLE PRECISION DEFAULT NULL, rsp_wsd_max DOUBLE PRECISION NOT NULL, rsp_esd_max DOUBLE PRECISION NOT NULL, rsp_win DOUBLE PRECISION NOT NULL, rsp_ein DOUBLE PRECISION NOT NULL, rsp_win_max DOUBLE PRECISION NOT NULL, rsp_ein_max DOUBLE PRECISION NOT NULL, rsp_wdr_gen DOUBLE PRECISION NOT NULL, rsp_edr_gen DOUBLE PRECISION NOT NULL, rsp_created_by INT NOT NULL, rsp_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_team (id INT AUTO_INCREMENT NOT NULL, rst_type INT DEFAULT NULL, rst_war DOUBLE PRECISION DEFAULT NULL, rst_ear DOUBLE PRECISION DEFAULT NULL, rst_wrr DOUBLE PRECISION DEFAULT NULL, rst_err DOUBLE PRECISION DEFAULT NULL, rst_wsd DOUBLE PRECISION DEFAULT NULL, rst_esd DOUBLE PRECISION DEFAULT NULL, rst_wdr DOUBLE PRECISION DEFAULT NULL, rst_edr DOUBLE PRECISION DEFAULT NULL, rst_wsd_max DOUBLE PRECISION NOT NULL, rst_esd_max DOUBLE PRECISION NOT NULL, rst_win DOUBLE PRECISION NOT NULL, rst_ein DOUBLE PRECISION NOT NULL, rst_win_max DOUBLE PRECISION NOT NULL, rst_ein_max DOUBLE PRECISION NOT NULL, rst_wdr_gen DOUBLE PRECISION NOT NULL, rst_edr_gen DOUBLE PRECISION NOT NULL, rst_created_by INT NOT NULL, rst_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, rol_name VARCHAR(10) NOT NULL, rol_created_by INT NOT NULL, rol_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage (id INT AUTO_INCREMENT NOT NULL, stg_complete TINYINT(1) NOT NULL, stg_name VARCHAR(255) NOT NULL, stg_mode INT NOT NULL, stg_visibility INT NOT NULL, stg_access_link VARCHAR(255) NOT NULL, stg_status INT NOT NULL, stg_desc VARCHAR(255) NOT NULL, stg_progress INT NOT NULL, stg_weight DOUBLE PRECISION NOT NULL, stg_definite_dates TINYINT(1) NOT NULL, stg_dperiod INT NOT NULL, stg_dfrequency VARCHAR(255) NOT NULL, stg_dorigin INT NOT NULL, stg_fperiod INT NOT NULL, stg_ffrequency VARCHAR(255) NOT NULL, stg_forigin INT NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddate DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_dealine_nb_days INT NOT NULL, stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, stg_created_by INT DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_reopened TINYINT(1) NOT NULL, stg_last_reopened DATETIME NOT NULL, stg_unstarted_notif TINYINT(1) NOT NULL, stg_uncompleted_notif TINYINT(1) NOT NULL, stg_unfinished_notif TINYINT(1) NOT NULL, stg_is_finalized TINYINT(1) NOT NULL, stg_deleted DATETIME NOT NULL, stg_gcompleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE state (id INT AUTO_INCREMENT NOT NULL, sta_abbr VARCHAR(255) NOT NULL, sta_fullname VARCHAR(255) NOT NULL, sta_name VARCHAR(255) NOT NULL, sta_created_by INT DEFAULT NULL, sta_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey (id INT AUTO_INCREMENT NOT NULL, sur_name VARCHAR(45) NOT NULL, sur_created_by INT NOT NULL, sur_inserted DATETIME NOT NULL, sur_state INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_field (id INT AUTO_INCREMENT NOT NULL, sfi_type VARCHAR(255) NOT NULL, sfi_is_mandatory TINYINT(1) NOT NULL, sfi_title VARCHAR(255) NOT NULL, sfi_position INT NOT NULL, sfi_description VARCHAR(255) NOT NULL, sfi_created_by INT NOT NULL, sfi_inserted DATETIME NOT NULL, sfi_upperbound INT NOT NULL, sfi_lowerbound INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_field_parameter (id INT AUTO_INCREMENT NOT NULL, sfp_value VARCHAR(255) NOT NULL, sfp_lowerbound DOUBLE PRECISION DEFAULT NULL, sfp_upperbound DOUBLE PRECISION DEFAULT NULL, sfp_step DOUBLE PRECISION DEFAULT NULL, sfp_created_by INT NOT NULL, sfp_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE target (id INT AUTO_INCREMENT NOT NULL, tgt_sign INT NOT NULL, tgt_value DOUBLE PRECISION NOT NULL, tgt_created_by INT DEFAULT NULL, tgt_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, tea_name VARCHAR(255) NOT NULL, tea_weight_ini DOUBLE PRECISION NOT NULL, tea_picture VARCHAR(10) DEFAULT NULL, tea_created_by INT NOT NULL, tea_inserted DATETIME NOT NULL, tea_deleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_user (id INT AUTO_INCREMENT NOT NULL, tus_leader TINYINT(1) NOT NULL, tus_created_by INT NOT NULL, tus_inserted DATETIME NOT NULL, tus_deleted DATETIME DEFAULT NULL, tus_is_deleted TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template (id INT AUTO_INCREMENT NOT NULL, tmp_name VARCHAR(255) NOT NULL, tmp_created_by INT NOT NULL, tmp_inserted DATETIME NOT NULL, tmp_deleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_activity (id INT AUTO_INCREMENT NOT NULL, act_simplified TINYINT(1) NOT NULL, act_name VARCHAR(255) NOT NULL, act_visibility VARCHAR(255) NOT NULL, act_objectives VARCHAR(255) NOT NULL, act_created_by INT NOT NULL, act_inserted DATETIME NOT NULL, act_saved DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_activity_user (id INT AUTO_INCREMENT NOT NULL, a_u_leader TINYINT(1) NOT NULL, a_u_type INT NOT NULL, a_u_m_weight DOUBLE PRECISION NOT NULL, a_u_precomment VARCHAR(10) NOT NULL, a_u_created_by INT DEFAULT NULL, a_u_inserted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_criterion (id INT AUTO_INCREMENT NOT NULL, icrt_type INT NOT NULL, crt_name VARCHAR(255) DEFAULT NULL, crt_weight DOUBLE PRECISION NOT NULL, crt_force_comment_compare TINYINT(1) NOT NULL, crt_force_comment_value DOUBLE PRECISION DEFAULT NULL, crt_force_comment_sign VARCHAR(255) DEFAULT NULL, crt_lowerbound DOUBLE PRECISION DEFAULT NULL, crt_upperbound DOUBLE PRECISION DEFAULT NULL, crt_step DOUBLE PRECISION DEFAULT NULL, crt_comment VARCHAR(255) NOT NULL, crt_created_by INT DEFAULT NULL, crt_inserted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_recurring (id INT AUTO_INCREMENT NOT NULL, rct_name VARCHAR(255) NOT NULL, rct_status INT NOT NULL, rct_timeframe VARCHAR(255) NOT NULL, rct_freq INT NOT NULL, rct_gsd_interval INT NOT NULL, rct_gsd_timeframe VARCHAR(255) NOT NULL, rct_ged_interval INT NOT NULL, rct_ged_timeframe VARCHAR(255) NOT NULL, rct_type INT NOT NULL, rct_lowerbound DOUBLE PRECISION NOT NULL, rct_upperbound DOUBLE PRECISION NOT NULL, rct_step DOUBLE PRECISION NOT NULL, rct_open_end TINYINT(1) NOT NULL, rct_startdate DATETIME NOT NULL, rct_enddate DATETIME NOT NULL, rct_same_part TINYINT(1) NOT NULL, rct_created_by INT NOT NULL, rct_inserted DATETIME NOT NULL, rct_deleted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_stage (id INT AUTO_INCREMENT NOT NULL, stg_weight DOUBLE PRECISION NOT NULL, stg_period INT NOT NULL, stg_frequency VARCHAR(255) NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddate DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_deadline_nb_days INT NOT NULL, stg_created_by VARCHAR(255) DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_mode INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE title (id INT AUTO_INCREMENT NOT NULL, tit_name VARCHAR(255) NOT NULL, tit_weight_ini DOUBLE PRECISION NOT NULL, tit_created_by INT NOT NULL, tit_inserted DATETIME NOT NULL, tit_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (usr_id INT AUTO_INCREMENT NOT NULL, usr_int TINYINT(1) NOT NULL, usr_firstname VARCHAR(255) NOT NULL, usr_lastname VARCHAR(255) NOT NULL, usr_username VARCHAR(255) NOT NULL, usr_nickname VARCHAR(255) NOT NULL, usr_birthdate DATETIME NOT NULL, usr_email VARCHAR(255) DEFAULT NULL, usr_password VARCHAR(255) DEFAULT NULL, usr_position_name VARCHAR(255) DEFAULT NULL, usr_picture VARCHAR(255) NOT NULL, usr_token VARCHAR(255) NOT NULL, usr_weight_ini DOUBLE PRECISION NOT NULL, usr_usr_weight_1y DOUBLE PRECISION NOT NULL, usr_weight_2y DOUBLE PRECISION NOT NULL, usr_weight_3y DOUBLE PRECISION NOT NULL, usr_weight_4y DOUBLE PRECISION NOT NULL, usr_weight_5y DOUBLE PRECISION NOT NULL, usr_act_archive_nb_days INT NOT NULL, usr_rm_token VARCHAR(255) NOT NULL, usr_validated DATETIME NOT NULL, usr_enabled_creating_user TINYINT(1) NOT NULL, usr_created_by INT NOT NULL, usr_inserted DATETIME NOT NULL, usr_last_connected DATETIME DEFAULT NULL, usr_deleted DATETIME NOT NULL, PRIMARY KEY(usr_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE weight (id INT AUTO_INCREMENT NOT NULL, wgt_interval INT NOT NULL, wgt_titleframe VARCHAR(255) NOT NULL, wgt_value DOUBLE PRECISION DEFAULT NULL, wgt_modified DATETIME DEFAULT NULL, wgt_created_by INT NOT NULL, wgt_inserted DATETIME NOT NULL, wgt_deleted DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_experience (id INT AUTO_INCREMENT NOT NULL, wex_active TINYINT(1) NOT NULL, wex_position VARCHAR(255) NOT NULL, wex_location VARCHAR(255) NOT NULL, wex_startdate DATETIME NOT NULL, wex_enddate DATETIME NOT NULL, wex_created_by INT NOT NULL, wex_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm (id INT AUTO_INCREMENT NOT NULL, wfi_hq_location VARCHAR(255) NOT NULL, wfi_hq_city VARCHAR(255) NOT NULL, wfi_hq_state VARCHAR(255) NOT NULL, wfi_hq_country VARCHAR(255) NOT NULL, wfi_logo VARCHAR(255) NOT NULL, wfi_website VARCHAR(255) NOT NULL, wfi_creation VARCHAR(255) NOT NULL, wfi_firm_type VARCHAR(255) NOT NULL, wfi_size INT NOT NULL, wfi_nb_lk_followers INT NOT NULL, wfi_nb_lk_employees INT NOT NULL, wfi_active TINYINT(1) NOT NULL, wfi_url VARCHAR(255) NOT NULL, wfi_name VARCHAR(255) NOT NULL, wfi_common_name VARCHAR(255) NOT NULL, wfi_mail_prefix INT NOT NULL, wfi_suffix VARCHAR(255) NOT NULL, wfi_nb_active_exp INT NOT NULL, wfi_created INT NOT NULL, wfi_created_by INT NOT NULL, wfi_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm_competency (id INT AUTO_INCREMENT NOT NULL, wfc_name VARCHAR(255) NOT NULL, wfc_created_by INT NOT NULL, wfc_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm_location (id INT AUTO_INCREMENT NOT NULL, wfl_hq_city VARCHAR(255) NOT NULL, wfl_hq_state VARCHAR(255) NOT NULL, wfl_hq_country VARCHAR(255) NOT NULL, wfl_created_by INT NOT NULL, wfl_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm_sector (id INT AUTO_INCREMENT NOT NULL, wfs_name VARCHAR(255) NOT NULL, wfs_created_by INT NOT NULL, wfs_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_individual (id INT AUTO_INCREMENT NOT NULL, win_lk_country VARCHAR(10) NOT NULL, win_lk_url VARCHAR(255) NOT NULL, win_lk_full_name VARCHAR(255) NOT NULL, win_lk_male TINYINT(1) NOT NULL, win_created INT NOT NULL, win_firstname VARCHAR(255) NOT NULL, win_lastname VARCHAR(255) NOT NULL, win_email VARCHAR(255) NOT NULL, win_gdpr DATETIME NOT NULL, win_lk_nb_connections INT NOT NULL, win_lk_contacted TINYINT(1) NOT NULL, win_created_by INT NOT NULL, win_inserted DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE user_tempo CHANGE username username VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_user');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE appreciation');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE criterion');
        $this->addSql('DROP TABLE criterion_group');
        $this->addSql('DROP TABLE criterion_name');
        $this->addSql('DROP TABLE decision');
        $this->addSql('DROP TABLE departement');
        $this->addSql('DROP TABLE external_user');
        $this->addSql('DROP TABLE generated_image');
        $this->addSql('DROP TABLE gpw');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE help');
        $this->addSql('DROP TABLE icon');
        $this->addSql('DROP TABLE insitution_process');
        $this->addSql('DROP TABLE iprocess_activity_user');
        $this->addSql('DROP TABLE iprocess_criterion');
        $this->addSql('DROP TABLE iprocess_stage');
        $this->addSql('DROP TABLE lkurl');
        $this->addSql('DROP TABLE mail');
        $this->addSql('DROP TABLE option_name');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_user_option');
        $this->addSql('DROP TABLE otpuser');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE process');
        $this->addSql('DROP TABLE process_criterion');
        $this->addSql('DROP TABLE process_stage');
        $this->addSql('DROP TABLE ranking');
        $this->addSql('DROP TABLE ranking_history');
        $this->addSql('DROP TABLE ranking_team');
        $this->addSql('DROP TABLE ranking_team_history');
        $this->addSql('DROP TABLE record');
        $this->addSql('DROP TABLE recurring');
        $this->addSql('DROP TABLE result');
        $this->addSql('DROP TABLE result_project');
        $this->addSql('DROP TABLE result_team');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE stage');
        $this->addSql('DROP TABLE state');
        $this->addSql('DROP TABLE survey');
        $this->addSql('DROP TABLE survey_field');
        $this->addSql('DROP TABLE survey_field_parameter');
        $this->addSql('DROP TABLE target');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_user');
        $this->addSql('DROP TABLE template');
        $this->addSql('DROP TABLE template_activity');
        $this->addSql('DROP TABLE template_activity_user');
        $this->addSql('DROP TABLE template_criterion');
        $this->addSql('DROP TABLE template_recurring');
        $this->addSql('DROP TABLE template_stage');
        $this->addSql('DROP TABLE title');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE weight');
        $this->addSql('DROP TABLE worker_experience');
        $this->addSql('DROP TABLE worker_firm');
        $this->addSql('DROP TABLE worker_firm_competency');
        $this->addSql('DROP TABLE worker_firm_location');
        $this->addSql('DROP TABLE worker_firm_sector');
        $this->addSql('DROP TABLE worker_individual');
        $this->addSql('ALTER TABLE user_tempo CHANGE username username VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
    }
}
