<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajout des relations mal définies dans la version silex de l'appli
 */
final class AjoutRelation2 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (act_id INT AUTO_INCREMENT NOT NULL, act_master_usr_id INT NOT NULL, process_id INT NOT NULL, institution_process_id INT DEFAULT NULL, organization_id INT NOT NULL, template_activity_act_id INT DEFAULT NULL, act_complete TINYINT(1) NOT NULL, act_magnitude INT NOT NULL, act_simplified TINYINT(1) NOT NULL, act_name VARCHAR(255) NOT NULL, act_visibility VARCHAR(255) NOT NULL, act_start_date DATETIME NOT NULL, act_end_date DATETIME NOT NULL, act_objectives VARCHAR(255) NOT NULL, act_status INT NOT NULL, act_progress DOUBLE PRECISION NOT NULL, act_isRewarding TINYINT(1) NOT NULL, act_distrAmount DOUBLE PRECISION NOT NULL, act_res_inertia DOUBLE PRECISION NOT NULL, act_res_benefit_eff DOUBLE PRECISION NOT NULL, act_createdBy INT NOT NULL, act_inserted DATETIME NOT NULL, act_saved DATETIME NOT NULL, act_isFinalized TINYINT(1) NOT NULL, act_finalized DATETIME DEFAULT NULL, act_deleted DATETIME NOT NULL, act_completed DATETIME NOT NULL, act_released DATETIME NOT NULL, act_archived DATETIME NOT NULL, INDEX IDX_AC74095A7EC2F574 (process_id), INDEX IDX_AC74095A98B600AE (institution_process_id), INDEX IDX_AC74095A32C8A3DE (organization_id), INDEX IDX_AC74095A7E1453AC (template_activity_act_id), INDEX IDX_AC74095A2267A676 (act_master_usr_id), PRIMARY KEY(act_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity_user (a_u_id INT AUTO_INCREMENT NOT NULL, team_tea_id INT NOT NULL, activity_act_id INT NOT NULL, stage_stg_id INT NOT NULL, criterion_crt_id INT DEFAULT NULL, user_usr_id INT DEFAULT NULL, external_user_ext_usr_id INT DEFAULT NULL, a_u_status INT NOT NULL, a_u_aw_result DOUBLE PRECISION DEFAULT NULL, a_u_ae_result DOUBLE PRECISION DEFAULT NULL, a_u_re_result DOUBLE PRECISION DEFAULT NULL, a_u_e_dev DOUBLE PRECISION DEFAULT NULL, a_u_w_devratio DOUBLE PRECISION DEFAULT NULL, a_u_e_devratio DOUBLE PRECISION DEFAULT NULL, a_u_leader TINYINT(1) NOT NULL, a_u_type INT NOT NULL, a_u_m_weight DOUBLE PRECISION NOT NULL, a_u_precomment VARCHAR(10) DEFAULT NULL, a_u_ivp_bonus DOUBLE PRECISION NOT NULL, a_u_ivp_penalty DOUBLE PRECISION NOT NULL, a_u_of_bonys DOUBLE PRECISION NOT NULL, a_u_of_penalty DOUBLE PRECISION NOT NULL, a_u_mailed TINYINT(1) DEFAULT NULL, a_u_created_by INT DEFAULT NULL, a_u_inserted DATETIME DEFAULT NULL, a_u_confirmed DATETIME DEFAULT NULL, a_u_deleted DATETIME DEFAULT NULL, INDEX IDX_8E570DDB1C22DDD4 (team_tea_id), INDEX IDX_8E570DDB83D3BB28 (activity_act_id), INDEX IDX_8E570DDB935EEA40 (stage_stg_id), INDEX IDX_8E570DDBD26A20E6 (criterion_crt_id), INDEX IDX_8E570DDB693BC8C6 (user_usr_id), INDEX IDX_8E570DDB310C5A5A (external_user_ext_usr_id), PRIMARY KEY(a_u_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE answer (asw_id INT AUTO_INCREMENT NOT NULL, survey_field_sfi_id INT NOT NULL, survey_sur_id INT NOT NULL, activity_user_a_u_id INT DEFAULT NULL, asw_text VARCHAR(255) NOT NULL, asw_created_by INT NOT NULL, asw_inserted DATETIME NOT NULL, INDEX IDX_DADD4A25AFBE78D8 (survey_field_sfi_id), INDEX IDX_DADD4A257D7E0D2A (survey_sur_id), INDEX IDX_DADD4A25661418FB (activity_user_a_u_id), PRIMARY KEY(asw_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appreciation (apt_id INT AUTO_INCREMENT NOT NULL, apt_criterion INT NOT NULL, apt_value DOUBLE PRECISION NOT NULL, apt_comment VARCHAR(255) NOT NULL, apt_created_by INT DEFAULT NULL, INDEX IDX_5CD4DEAB64340EC6 (apt_criterion), PRIMARY KEY(apt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city (cit_id INT AUTO_INCREMENT NOT NULL, state_sta_id INT NOT NULL, country_cou_id INT NOT NULL, cit_abbr VARCHAR(255) NOT NULL, cit_fullname VARCHAR(255) NOT NULL, cit_name VARCHAR(255) NOT NULL, cit_created_by INT DEFAULT NULL, cit_inserted DATETIME NOT NULL, INDEX IDX_2D5B02342378CB28 (state_sta_id), INDEX IDX_2D5B0234A1599B34 (country_cou_id), PRIMARY KEY(cit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (cli_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, client_org_id INT NOT NULL, worker_firm_wfi_id INT DEFAULT NULL, clicommname VARCHAR(255) NOT NULL, cli_type VARCHAR(255) NOT NULL, cli_logo VARCHAR(255) NOT NULL, cli_email VARCHAR(255) DEFAULT NULL, cli_created_by INT NOT NULL, cli_inserted DATETIME NOT NULL, INDEX IDX_C7440455F10DACEE (organization_org_id), INDEX IDX_C7440455A12537A8 (client_org_id), UNIQUE INDEX UNIQ_C7440455A8C102B2 (worker_firm_wfi_id), PRIMARY KEY(cli_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (con_id INT AUTO_INCREMENT NOT NULL, con_locale VARCHAR(255) NOT NULL, con_type VARCHAR(255) NOT NULL, con_sent TINYINT(1) NOT NULL, con_fullname VARCHAR(255) NOT NULL, con_compagny VARCHAR(255) NOT NULL, con_adress VARCHAR(255) NOT NULL, con_zip_code INT NOT NULL, con_city VARCHAR(255) NOT NULL, con_country VARCHAR(255) NOT NULL, con_position VARCHAR(255) NOT NULL, con_email VARCHAR(255) NOT NULL, con_message VARCHAR(255) NOT NULL, con_newsletter TINYINT(1) NOT NULL, con_doc TINYINT(1) NOT NULL, con_mdate DATETIME NOT NULL, con_mtime DATETIME NOT NULL, con_inserted DATETIME NOT NULL, con_confirmed DATETIME NOT NULL, con_created_by INT DEFAULT NULL, PRIMARY KEY(con_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country (cou_id INT AUTO_INCREMENT NOT NULL, cou_abbr VARCHAR(255) NOT NULL, cou_fullname VARCHAR(255) NOT NULL, cou_name VARCHAR(255) NOT NULL, cou_created_by INT DEFAULT NULL, cou_inserted DATETIME NOT NULL, PRIMARY KEY(cou_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterion (crt_id INT AUTO_INCREMENT NOT NULL, stage_stg_id INT DEFAULT NULL, organization_org_id INT DEFAULT NULL, criterion_name_cna_id INT DEFAULT NULL, cri_complete TINYINT(1) NOT NULL, cri_type INT NOT NULL, cri_name VARCHAR(255) NOT NULL, cri_weight DOUBLE PRECISION NOT NULL, cri_force_comment_compare TINYINT(1) NOT NULL, cri_force_comment_value DOUBLE PRECISION DEFAULT NULL, cri_force_comment_sign VARCHAR(255) DEFAULT NULL, cri_lowerbound DOUBLE PRECISION DEFAULT NULL, cri_upperbound DOUBLE PRECISION DEFAULT NULL, cri_step DOUBLE PRECISION DEFAULT NULL, cri_grade_type INT NOT NULL, cri_avg_ae_res DOUBLE PRECISION NOT NULL, cri_avg_rw_res VARCHAR(255) NOT NULL, cri_avg_re_res DOUBLE PRECISION NOT NULL, cri_max_w_dev DOUBLE PRECISION NOT NULL, cri_max_e_dev DOUBLE PRECISION NOT NULL, cri_avg_w_dev DOUBLE PRECISION NOT NULL, cri_avg_e_dev DOUBLE PRECISION NOT NULL, cri_w_inertia DOUBLE PRECISION NOT NULL, cri_e_inertia DOUBLE PRECISION NOT NULL, cri_max_w_inertia DOUBLE PRECISION NOT NULL, cri_max_e_inertia DOUBLE PRECISION NOT NULL, cri_w_distratio DOUBLE PRECISION NOT NULL, cri_comment VARCHAR(255) NOT NULL, cri_created_by INT DEFAULT NULL, cri_inserted DATETIME DEFAULT NULL, cri_deleted DATETIME DEFAULT NULL, INDEX IDX_7C822271935EEA40 (stage_stg_id), INDEX IDX_7C822271F10DACEE (organization_org_id), INDEX IDX_7C822271CE87AAFC (criterion_name_cna_id), PRIMARY KEY(crt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterion_group (cgp_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT DEFAULT NULL, department_dpt_id INT DEFAULT NULL, cgp_created_by INT NOT NULL, cgp_inserted DATETIME NOT NULL, cgp_name VARCHAR(255) NOT NULL, INDEX IDX_863CE5DDF10DACEE (organization_org_id), INDEX IDX_863CE5DDB232D839 (department_dpt_id), PRIMARY KEY(cgp_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterion_name (cna_id INT AUTO_INCREMENT NOT NULL, icon_ico_id INT NOT NULL, organization_org_id INT NOT NULL, department_dpt_id INT DEFAULT NULL, criterion_group_cgp_id INT DEFAULT NULL, cna_type INT NOT NULL, cna_name VARCHAR(255) NOT NULL, can_unit VARCHAR(255) NOT NULL, can_created_by INT NOT NULL, can_inserted DATETIME NOT NULL, INDEX IDX_ACB459C3E2C46BF8 (icon_ico_id), INDEX IDX_ACB459C3F10DACEE (organization_org_id), INDEX IDX_ACB459C3B232D839 (department_dpt_id), INDEX IDX_ACB459C33FC278E3 (criterion_group_cgp_id), PRIMARY KEY(cna_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE decision (dec_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT DEFAULT NULL, activity_act_id INT DEFAULT NULL, stage_stg_id INT DEFAULT NULL, dec_type INT NOT NULL, req_anon INT NOT NULL, dec_anon TINYINT(1) DEFAULT NULL, val_usr_id INT NOT NULL, dec_result INT NOT NULL, dec_created_by INT NOT NULL, dec_inserted DATETIME NOT NULL, dec_decided DATETIME NOT NULL, dec_validated DATETIME NOT NULL, req_usr_id INT NOT NULL, dec_usr_id INT NOT NULL, INDEX IDX_84ACBE48F10DACEE (organization_org_id), INDEX IDX_84ACBE4883D3BB28 (activity_act_id), INDEX IDX_84ACBE48935EEA40 (stage_stg_id), PRIMARY KEY(dec_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE department (dpt_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, dpt_name VARCHAR(45) NOT NULL, dpt_created_by INT NOT NULL, dpt_inserted DATETIME NOT NULL, dpt_deleted DATETIME DEFAULT NULL, masterUser_usr_id INT NOT NULL, INDEX IDX_CD1DE18A84F215E7 (masterUser_usr_id), INDEX IDX_CD1DE18AF10DACEE (organization_org_id), PRIMARY KEY(dpt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE external_user (ext_id INT AUTO_INCREMENT NOT NULL, user_usr_id INT DEFAULT NULL, client_cli_id INT NOT NULL, ext_fisrtname VARCHAR(255) NOT NULL, ext_lastname VARCHAR(255) NOT NULL, ext_email VARCHAR(255) DEFAULT NULL, ext_position_name VARCHAR(255) NOT NULL, ext_weight_value DOUBLE PRECISION NOT NULL, ext_owner TINYINT(1) NOT NULL, ext_created_by INT NOT NULL, ext_inserted DATETIME NOT NULL, ext_last_connected DATETIME DEFAULT NULL, ext_deleted DATETIME DEFAULT NULL, INDEX IDX_188CB665693BC8C6 (user_usr_id), INDEX IDX_188CB665E9E8A903 (client_cli_id), PRIMARY KEY(ext_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE generated_image (gim_id INT AUTO_INCREMENT NOT NULL, criterion_name_cna_id INT DEFAULT NULL, gim_all INT NOT NULL, gim_type INT NOT NULL, gim_tid INT DEFAULT NULL, gim_uid INT DEFAULT NULL, gim_aid INT DEFAULT NULL, gim_ov TINYINT(1) NOT NULL, gim_sid INT DEFAULT NULL, gim_role INT DEFAULT NULL, gim_created_by INT DEFAULT NULL, gim_val VARCHAR(255) NOT NULL, gim_inserted DATETIME NOT NULL, UNIQUE INDEX UNIQ_6E67FC40CE87AAFC (criterion_name_cna_id), PRIMARY KEY(gim_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gpw (gpw_id INT AUTO_INCREMENT NOT NULL, gpw_pid VARCHAR(255) NOT NULL, gpw_firm VARCHAR(255) NOT NULL, gpw_sector VARCHAR(255) NOT NULL, gpw_location VARCHAR(255) NOT NULL, gpw_c_date INT NOT NULL, gpw_nb_workers INT NOT NULL, gpw_website VARCHAR(255) NOT NULL, gpw_gen_mail VARCHAR(255) NOT NULL, gpw_fb VARCHAR(255) NOT NULL, gpw_linked_in VARCHAR(255) NOT NULL, gpw_twitter VARCHAR(255) NOT NULL, gpw_xing VARCHAR(255) NOT NULL, gpw_yt VARCHAR(255) NOT NULL, gpw_insta VARCHAR(255) NOT NULL, gpw_contact_name VARCHAR(255) NOT NULL, gpw_contact_position VARCHAR(255) NOT NULL, gpw_contact_mail VARCHAR(255) NOT NULL, gpw_contact_tel VARCHAR(255) NOT NULL, gpw_values_careers_inspiration VARCHAR(255) NOT NULL, gpw_employee_author VARCHAR(255) NOT NULL, gpw_employee_position VARCHAR(255) NOT NULL, gpw_employee_comment VARCHAR(255) NOT NULL, gpw_boss_author VARCHAR(255) NOT NULL, gpw_boss_division VARCHAR(255) NOT NULL, gpw_boss_comment VARCHAR(255) NOT NULL, gpw_award_year_1 VARCHAR(255) NOT NULL, gpw_award_title_1 VARCHAR(255) NOT NULL, gpw_award_rnk_1 VARCHAR(255) NOT NULL, gpw_award_year_2 VARCHAR(255) NOT NULL, gpw_award_title_2 VARCHAR(255) NOT NULL, gpw_award_rnk_2 VARCHAR(255) NOT NULL, gpw_award_year_3 VARCHAR(255) NOT NULL, gpw_award_title_3 VARCHAR(255) NOT NULL, gpw_award_rnk3 VARCHAR(255) NOT NULL, gpw_survey_text_1 VARCHAR(255) NOT NULL, gpw_survey_res_1 VARCHAR(255) NOT NULL, gpw_survey_text_2 VARCHAR(255) NOT NULL, gpw_survey_res_2 VARCHAR(255) NOT NULL, gpw_survey_text_3 VARCHAR(255) NOT NULL, gpw_survey_res_3 VARCHAR(255) NOT NULL, gpw_survey_text_4 VARCHAR(255) NOT NULL, gpw_survey_res_4 VARCHAR(255) NOT NULL, gpw_survey_text_5 VARCHAR(255) NOT NULL, gpw_survey_res_5 VARCHAR(255) NOT NULL, gpw_survey_text_6 VARCHAR(255) NOT NULL, gpw_survey_res_6 VARCHAR(255) NOT NULL, gpw_survey_text_7 VARCHAR(255) NOT NULL, gpw_survey_res_7 VARCHAR(255) NOT NULL, gpw_created_by INT DEFAULT NULL, gpw_inserted DATETIME NOT NULL, PRIMARY KEY(gpw_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grade (grd_id INT AUTO_INCREMENT NOT NULL, activity_user_team_tea_id INT DEFAULT NULL, activity_user_user_usr_id INT NOT NULL, activity_act_id INT NOT NULL, criterion_crt_id INT NOT NULL, stage_stg_id INT NOT NULL, grd_type INT NOT NULL, grd_graded_usr_id INT NOT NULL, grd_graded_tea_id INT NOT NULL, grd_value DOUBLE PRECISION NOT NULL, grd_comment VARCHAR(255) DEFAULT NULL, grd_created_by INT DEFAULT NULL, grd_inserted DATETIME NOT NULL, INDEX IDX_595AAE34517AF523 (activity_user_team_tea_id), INDEX IDX_595AAE342463E031 (activity_user_user_usr_id), INDEX IDX_595AAE3483D3BB28 (activity_act_id), INDEX IDX_595AAE34D26A20E6 (criterion_crt_id), INDEX IDX_595AAE34935EEA40 (stage_stg_id), PRIMARY KEY(grd_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE icon (ico_id INT AUTO_INCREMENT NOT NULL, ico_type VARCHAR(255) NOT NULL, ico_name VARCHAR(255) NOT NULL, ico_unicode VARCHAR(255) NOT NULL, ico_created_by INT DEFAULT NULL, ico_inserted DATETIME NOT NULL, PRIMARY KEY(ico_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE institution_process (inp_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, process_pro_id INT NOT NULL, parent_id INT DEFAULT NULL, inp_name VARCHAR(255) NOT NULL, inp_approvable TINYINT(1) NOT NULL, inp_gradable TINYINT(1) NOT NULL, inp_created_by INT NOT NULL, inp_isnerted DATETIME NOT NULL, inp_deleted DATETIME DEFAULT NULL, masterUser_usr_id INT NOT NULL, INDEX IDX_E2E3EE04F10DACEE (organization_org_id), INDEX IDX_E2E3EE0495B7A1D (process_pro_id), INDEX IDX_E2E3EE0484F215E7 (masterUser_usr_id), UNIQUE INDEX UNIQ_E2E3EE04727ACA70 (parent_id), PRIMARY KEY(inp_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE iprocess_activity_user (a_u_id INT AUTO_INCREMENT NOT NULL, team_tea_id INT NOT NULL, iprocess_inp_id INT NOT NULL, iprocess_stage_stg_id INT NOT NULL, iprocess_criterion_crt_id INT DEFAULT NULL, user_usr_id INT DEFAULT NULL, external_user_ext_usr_id INT NOT NULL, a_u_status INT NOT NULL, a_u_leader TINYINT(1) NOT NULL, a_u_type INT NOT NULL, a_u_m_weight DOUBLE PRECISION NOT NULL, a_u_precomment VARCHAR(255) NOT NULL, a_u_created_by INT DEFAULT NULL, a_u_inserted DATETIME DEFAULT NULL, a_u_deleted DATETIME NOT NULL, INDEX IDX_DA74341B1C22DDD4 (team_tea_id), INDEX IDX_DA74341BB2CC3CA8 (iprocess_inp_id), INDEX IDX_DA74341B6E3003B6 (iprocess_stage_stg_id), INDEX IDX_DA74341BEF264A3A (iprocess_criterion_crt_id), INDEX IDX_DA74341B693BC8C6 (user_usr_id), INDEX IDX_DA74341B310C5A5A (external_user_ext_usr_id), PRIMARY KEY(a_u_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE iprocess_criterion (crt_id INT AUTO_INCREMENT NOT NULL, iprocess_stage_stg_id INT DEFAULT NULL, iprocess_inp_id INT DEFAULT NULL, criterion_name_cna_id INT DEFAULT NULL, crt_type INT NOT NULL, crt_name VARCHAR(255) DEFAULT NULL, crt_weight DOUBLE PRECISION NOT NULL, crt_force_comment_compare TINYINT(1) NOT NULL, crt_force_comment_value DOUBLE PRECISION DEFAULT NULL, crt_force_comment_sign VARCHAR(255) DEFAULT NULL, crt_lower_bound DOUBLE PRECISION DEFAULT NULL, crt_upperbound DOUBLE PRECISION DEFAULT NULL, crt_step DOUBLE PRECISION DEFAULT NULL, crt_comment VARCHAR(255) NOT NULL, crt_created_by INT DEFAULT NULL, crt_inserted DATETIME DEFAULT NULL, INDEX IDX_57F78ED46E3003B6 (iprocess_stage_stg_id), INDEX IDX_57F78ED4B2CC3CA8 (iprocess_inp_id), UNIQUE INDEX UNIQ_57F78ED4CE87AAFC (criterion_name_cna_id), PRIMARY KEY(crt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE iprocess_stage (stg_id INT AUTO_INCREMENT NOT NULL, iprocess_inp_id INT NOT NULL, organization_org_id INT DEFAULT NULL, stg_master_usr_id INT NOT NULL, stg_complete TINYINT(1) NOT NULL, stg_name VARCHAR(255) NOT NULL, stg_mod INT NOT NULL, stg_visibility INT NOT NULL, stg_status DOUBLE PRECISION NOT NULL, stg_desc VARCHAR(255) NOT NULL, stg_progress DOUBLE PRECISION NOT NULL, stg_weight DOUBLE PRECISION NOT NULL, stg_dperiod INT NOT NULL, stg_dfrequency VARCHAR(255) NOT NULL, stg_dorigin INT NOT NULL, stg_ffrequency VARCHAR(255) NOT NULL, stg_forigin INT NOT NULL, stg_definite_dates TINYINT(1) NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddate DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_deadline_nb_days INT NOT NULL, stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, stg_created_by INT DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_is_finalized TINYINT(1) NOT NULL, stg_finalized DATETIME NOT NULL, stg_deleted DATETIME NOT NULL, stg_gcompleted DATETIME NOT NULL, INDEX IDX_6864F1B4B2CC3CA8 (iprocess_inp_id), INDEX IDX_6864F1B4F10DACEE (organization_org_id), INDEX IDX_6864F1B4AFCB9C11 (stg_master_usr_id), PRIMARY KEY(stg_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lkurl (lk_url_id INT AUTO_INCREMENT NOT NULL, lk_url_country VARCHAR(10) NOT NULL, lk_url_letter VARCHAR(10) NOT NULL, lk_url_pag_nb VARCHAR(10) NOT NULL, lk_url_value VARCHAR(10) NOT NULL, lk_url_created_by INT NOT NULL, lk_url_inserted DATETIME NOT NULL, PRIMARY KEY(lk_url_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mail (mail_id INT AUTO_INCREMENT NOT NULL, user_usr_id INT NOT NULL, worker_individual_win_id INT NOT NULL, organization_org_id INT NOT NULL, worker_firm_wfi_id INT NOT NULL, activity_act_id INT NOT NULL, stage_stg_id INT NOT NULL, mail_persona VARCHAR(1) NOT NULL, mail_token VARCHAR(255) NOT NULL, mail_read DATETIME NOT NULL, mail_created_by INT NOT NULL, mail_inserted DATETIME NOT NULL, mail_language VARCHAR(3) NOT NULL, INDEX IDX_5126AC48693BC8C6 (user_usr_id), INDEX IDX_5126AC48B1623D83 (worker_individual_win_id), INDEX IDX_5126AC48F10DACEE (organization_org_id), INDEX IDX_5126AC48A8C102B2 (worker_firm_wfi_id), INDEX IDX_5126AC4883D3BB28 (activity_act_id), INDEX IDX_5126AC48935EEA40 (stage_stg_id), PRIMARY KEY(mail_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE option_name (ona_id INT AUTO_INCREMENT NOT NULL, ona_type INT NOT NULL, ona_name VARCHAR(255) NOT NULL, ona_description VARCHAR(255) NOT NULL, ona_created_by DATETIME NOT NULL, ona_inserted DATETIME NOT NULL, PRIMARY KEY(ona_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization (org_id INT AUTO_INCREMENT NOT NULL, worker_firm_wfi_id INT DEFAULT NULL, org_legalname VARCHAR(255) NOT NULL, org_commname VARCHAR(255) NOT NULL, org_type VARCHAR(255) NOT NULL, org_is_client TINYINT(1) NOT NULL, org_oth_language VARCHAR(255) NOT NULL, org_weight_type VARCHAR(255) NOT NULL, org_created_by INT NOT NULL, org_inserted DATETIME NOT NULL, org_validated DATETIME NOT NULL, org_expired DATETIME NOT NULL, org_testing_reminder_sent TINYINT(1) NOT NULL, org_deleted DATETIME DEFAULT NULL, org_routine_pstatus DATETIME DEFAULT NULL, org_routine_greminders DATETIME DEFAULT NULL, org_users_CSV VARCHAR(255) NOT NULL, org_logo VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C1EE637CA8C102B2 (worker_firm_wfi_id), PRIMARY KEY(org_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organization_user_option (opt_id INT AUTO_INCREMENT NOT NULL, option_name_ona_id INT DEFAULT NULL, organization_org_id INT NOT NULL, department_dpt_id INT DEFAULT NULL, position_pos_id INT DEFAULT NULL, title_tit_id INT DEFAULT NULL, user_usr_id INT DEFAULT NULL, role_rol_id INT NOT NULL, opt_bool_value TINYINT(1) NOT NULL, opt_int_value DOUBLE PRECISION NOT NULL, opt_int_value_2 DOUBLE PRECISION NOT NULL, opt_float_value DOUBLE PRECISION NOT NULL, pot_string_value VARCHAR(255) NOT NULL, opt_enabled TINYINT(1) NOT NULL, opt_created_by INT DEFAULT NULL, opt_inserted DATETIME NOT NULL, UNIQUE INDEX UNIQ_F88BFF654B493BD (option_name_ona_id), INDEX IDX_F88BFF6F10DACEE (organization_org_id), INDEX IDX_F88BFF6B232D839 (department_dpt_id), INDEX IDX_F88BFF6B9E63123 (position_pos_id), INDEX IDX_F88BFF66AFC588 (title_tit_id), INDEX IDX_F88BFF6693BC8C6 (user_usr_id), INDEX IDX_F88BFF6AF9C58DD (role_rol_id), PRIMARY KEY(opt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE otpuser (otp_id INT AUTO_INCREMENT NOT NULL, otp_organization INT NOT NULL, otp_type VARCHAR(1) NOT NULL, otp_fullname VARCHAR(255) NOT NULL, otp_tipe VARCHAR(255) NOT NULL, otp_email VARCHAR(255) NOT NULL, otp_created_by INT DEFAULT NULL, otp_inserted DATETIME NOT NULL, INDEX IDX_2524453FA99EEA35 (otp_organization), PRIMARY KEY(otp_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE position (pos_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, department_dpt_id INT DEFAULT NULL, pos_name VARCHAR(255) NOT NULL, pos_weight_ini DOUBLE PRECISION NOT NULL, pos_weight_1y DOUBLE PRECISION NOT NULL, pos_weight_2y DOUBLE PRECISION NOT NULL, pos_weight_3y DOUBLE PRECISION NOT NULL, pos_weight_4y DOUBLE PRECISION NOT NULL, pos_weight_5y DOUBLE PRECISION NOT NULL, pos_created_by INT NOT NULL, pos_inserted DATETIME NOT NULL, pos_deleted DATETIME DEFAULT NULL, INDEX IDX_462CE4F5F10DACEE (organization_org_id), INDEX IDX_462CE4F5B232D839 (department_dpt_id), PRIMARY KEY(pos_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE process (pro_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, parent_id INT DEFAULT NULL, icon_ico_id INT NOT NULL, pro_name VARCHAR(255) NOT NULL, pro_approvable TINYINT(1) NOT NULL, pro_gradable TINYINT(1) NOT NULL, pro_created_by INT NOT NULL, pro_inserted DATETIME NOT NULL, pro_deleted DATETIME DEFAULT NULL, INDEX IDX_861D1896F10DACEE (organization_org_id), INDEX IDX_861D1896727ACA70 (parent_id), INDEX IDX_861D1896E2C46BF8 (icon_ico_id), PRIMARY KEY(pro_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE process_criterion (crt_id INT AUTO_INCREMENT NOT NULL, process_stage_stg_id INT DEFAULT NULL, process_pro_id INT DEFAULT NULL, criterion_name_cna_id INT DEFAULT NULL, crt_type INT NOT NULL, crt_name VARCHAR(255) DEFAULT NULL, crt_weight DOUBLE PRECISION NOT NULL, crt_force_comment_compare TINYINT(1) NOT NULL, crt_force_comment_value DOUBLE PRECISION DEFAULT NULL, crt_force_comment_sign VARCHAR(255) DEFAULT NULL, crt_lowerbound DOUBLE PRECISION DEFAULT NULL, crt_upperbound DOUBLE PRECISION DEFAULT NULL, crt_step DOUBLE PRECISION DEFAULT NULL, crt_comment VARCHAR(255) DEFAULT NULL, crt_created_by INT DEFAULT NULL, crt_inserted DATETIME DEFAULT NULL, INDEX IDX_E6CB6099F9E0BF71 (process_stage_stg_id), INDEX IDX_E6CB609995B7A1D (process_pro_id), UNIQUE INDEX UNIQ_E6CB6099CE87AAFC (criterion_name_cna_id), PRIMARY KEY(crt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE process_stage (stg_id INT AUTO_INCREMENT NOT NULL, process_pro_id INT NOT NULL, organization_org_id INT DEFAULT NULL, stg_master_usr_id INT NOT NULL, stg_complete TINYINT(1) NOT NULL, stg_name VARCHAR(255) NOT NULL, stg_mode VARCHAR(255) NOT NULL, stg_visibility INT NOT NULL, stg_definite_dates TINYINT(1) NOT NULL, stg_status DOUBLE PRECISION NOT NULL, stg_desc VARCHAR(255) NOT NULL, stg_progress DOUBLE PRECISION NOT NULL, stg_weight VARCHAR(255) NOT NULL, stg_dperiod INT NOT NULL, stg_dfrequency VARCHAR(255) NOT NULL, stg_dorigin INT NOT NULL, stg_fperiod INT NOT NULL, stg_ffrequency VARCHAR(255) NOT NULL, stg_forigin INT NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddated DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_dealine_nb_days INT NOT NULL, stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, stg_created_by INT DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_is_finalized DATETIME NOT NULL, stg_deleted DATETIME NOT NULL, stg_dcompleted DATETIME NOT NULL, INDEX IDX_9420BE9895B7A1D (process_pro_id), INDEX IDX_9420BE98F10DACEE (organization_org_id), INDEX IDX_9420BE98AFCB9C11 (stg_master_usr_id), PRIMARY KEY(stg_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking (rnk_id INT AUTO_INCREMENT NOT NULL, rnk_activity INT NOT NULL, rnk_stage INT DEFAULT NULL, rnk_criterion INT DEFAULT NULL, rnk_organization INT NOT NULL, rnk_user_usr_id INT DEFAULT NULL, rnk_dtype VARCHAR(1) NOT NULL, rnk_wtype VARCHAR(1) NOT NULL, rnk_abs_result INT NOT NULL, rnk_rel_result DOUBLE PRECISION NOT NULL, rnk_period INT NOT NULL, rnk_freq INT NOT NULL, rnk_value DOUBLE PRECISION NOT NULL, rnk_series_pop INT NOT NULL, rnk_created_by INT DEFAULT NULL, rnk_inserted DATETIME NOT NULL, rnk_updated DATETIME NOT NULL, INDEX IDX_80B839D0FCBCC329 (rnk_activity), INDEX IDX_80B839D08D0A8B3D (rnk_stage), INDEX IDX_80B839D0B5DECA3D (rnk_criterion), INDEX IDX_80B839D04C14732A (rnk_organization), INDEX IDX_80B839D09B266BD9 (rnk_user_usr_id), PRIMARY KEY(rnk_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking_history (rkh_id INT AUTO_INCREMENT NOT NULL, rkh_activity INT NOT NULL, rkh_stage INT DEFAULT NULL, rkh_criterion INT DEFAULT NULL, rhk_user_usr_id INT DEFAULT NULL, rkh_wtype VARCHAR(1) NOT NULL, rkh_abs_result INT NOT NULL, rkh_rel_result DOUBLE PRECISION NOT NULL, rkh_period INT NOT NULL, rkh_freq INT NOT NULL, rkh_value DOUBLE PRECISION NOT NULL, rkh_series_pop INT NOT NULL, rkh_created_by INT DEFAULT NULL, rkh_inserted DATETIME NOT NULL, INDEX IDX_2F6B262166DCD468 (rkh_activity), INDEX IDX_2F6B2621F4029FC4 (rkh_stage), INDEX IDX_2F6B2621B49FDB2C (rkh_criterion), INDEX IDX_2F6B262163E4206F (rhk_user_usr_id), PRIMARY KEY(rkh_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking_team (rkt_id INT AUTO_INCREMENT NOT NULL, rkt_activity INT NOT NULL, rkt_stage INT DEFAULT NULL, rkt_criterion INT DEFAULT NULL, team_tea_id INT NOT NULL, rkt_organization INT NOT NULL, rkt_dtype VARCHAR(1) NOT NULL, rkt_wtype VARCHAR(1) NOT NULL, rkt_abs_result INT NOT NULL, rkt_rel_result DOUBLE PRECISION NOT NULL, rkt_period INT NOT NULL, rkt_freq INT NOT NULL, rkt_value DOUBLE PRECISION NOT NULL, rkt_series_pop INT NOT NULL, rkt_created_by INT DEFAULT NULL, rkt_inserted DATETIME NOT NULL, rkt_updated DATETIME NOT NULL, INDEX IDX_6DDD29955B4EB50E (rkt_activity), INDEX IDX_6DDD2995547C697E (rkt_stage), INDEX IDX_6DDD299510738D20 (rkt_criterion), INDEX IDX_6DDD29951C22DDD4 (team_tea_id), INDEX IDX_6DDD29954FB5453B (rkt_organization), PRIMARY KEY(rkt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ranking_team_history (rth_id INT AUTO_INCREMENT NOT NULL, rth_activity INT NOT NULL, rth_stage INT DEFAULT NULL, rth_criterion INT DEFAULT NULL, team_tea_id INT NOT NULL, rth_organization INT NOT NULL, rth_dtype VARCHAR(1) NOT NULL, rth_wtype VARCHAR(1) NOT NULL, rth_abs_result INT NOT NULL, rth_rel_result DOUBLE PRECISION NOT NULL, rth_period INT NOT NULL, rth_freq INT NOT NULL, rth_value DOUBLE PRECISION NOT NULL, rth_series_pop INT NOT NULL, rth_creatd_by INT DEFAULT NULL, rth_inserted DATETIME NOT NULL, INDEX IDX_A1B5EBE15BD2E465 (rth_activity), INDEX IDX_A1B5EBE15199BC43 (rth_stage), INDEX IDX_A1B5EBE1CA13A9A1 (rth_criterion), INDEX IDX_A1B5EBE11C22DDD4 (team_tea_id), INDEX IDX_A1B5EBE11318B4A8 (rth_organization), PRIMARY KEY(rth_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE record (rec_entity VARCHAR(255) NOT NULL, rec_table_id INT NOT NULL, rec_property VARCHAR(255) NOT NULL, rec_old VARCHAR(255) NOT NULL, rec_new VARCHAR(255) NOT NULL, PRIMARY KEY(rec_entity)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE recurring (rct_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, rec_master_user_id INT DEFAULT NULL, rct_name VARCHAR(255) NOT NULL, rct_status INT NOT NULL, rct_timeframe VARCHAR(255) NOT NULL, rct_freq INT NOT NULL, rct_gsd_interval INT NOT NULL, rct_gsd_timeframe VARCHAR(255) NOT NULL, rct_ged_interval INT NOT NULL, rct_ged_timeframe VARCHAR(255) NOT NULL, rct_type INT NOT NULL, rct_lowerbound DOUBLE PRECISION NOT NULL, rct_upperbound DOUBLE PRECISION NOT NULL, rct_step DOUBLE PRECISION NOT NULL, rct_opend_end TINYINT(1) NOT NULL, rct_startdate DATETIME NOT NULL, rct_enddate DATETIME NOT NULL, rct_same_part TINYINT(1) NOT NULL, rct_created_by INT DEFAULT NULL, rct_inserted DATETIME NOT NULL, rct_deleted DATETIME DEFAULT NULL, INDEX IDX_6C6C02EDF10DACEE (organization_org_id), INDEX IDX_6C6C02ED4C86D2E4 (rec_master_user_id), PRIMARY KEY(rct_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result (res_id INT AUTO_INCREMENT NOT NULL, activity_act_id INT DEFAULT NULL, stage_stg_id INT DEFAULT NULL, criterion_crt_id INT DEFAULT NULL, user_usr_id INT DEFAULT NULL, external_user_ext_id_id INT DEFAULT NULL, res_type INT DEFAULT NULL, res_war DOUBLE PRECISION DEFAULT NULL, res_ear DOUBLE PRECISION DEFAULT NULL, res_wrr DOUBLE PRECISION DEFAULT NULL, res_err DOUBLE PRECISION DEFAULT NULL, res_wsd DOUBLE PRECISION DEFAULT NULL, res_esd DOUBLE PRECISION DEFAULT NULL, res_wdf DOUBLE PRECISION DEFAULT NULL, res_edr DOUBLE PRECISION DEFAULT NULL, res_wsd_max DOUBLE PRECISION DEFAULT NULL, res_esd_max DOUBLE PRECISION NOT NULL, res_win DOUBLE PRECISION NOT NULL, res_ein DOUBLE PRECISION NOT NULL, res_win_max DOUBLE PRECISION NOT NULL, res_ein_max DOUBLE PRECISION NOT NULL, res_wdr_gen DOUBLE PRECISION NOT NULL, res_res_der_gen DOUBLE PRECISION NOT NULL, res_created_by INT DEFAULT NULL, res_inserted DATETIME NOT NULL, INDEX IDX_136AC11383D3BB28 (activity_act_id), INDEX IDX_136AC113935EEA40 (stage_stg_id), INDEX IDX_136AC113D26A20E6 (criterion_crt_id), INDEX IDX_136AC113693BC8C6 (user_usr_id), INDEX IDX_136AC113C258E832 (external_user_ext_id_id), PRIMARY KEY(res_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_project (rsp_id INT AUTO_INCREMENT NOT NULL, activity_act_id INT DEFAULT NULL, stage_stg_id INT DEFAULT NULL, criterion_crt_id INT DEFAULT NULL, rsp_type INT DEFAULT NULL, rsp_war DOUBLE PRECISION DEFAULT NULL, rsp_ear DOUBLE PRECISION DEFAULT NULL, rsp_wrr DOUBLE PRECISION DEFAULT NULL, rsp_err DOUBLE PRECISION DEFAULT NULL, rsp_wsd DOUBLE PRECISION DEFAULT NULL, rsp_esd DOUBLE PRECISION DEFAULT NULL, rsp_wdr DOUBLE PRECISION DEFAULT NULL, rsp_edr DOUBLE PRECISION DEFAULT NULL, rsp_wsd_max DOUBLE PRECISION NOT NULL, rsp_esd_max DOUBLE PRECISION NOT NULL, rsp_win DOUBLE PRECISION NOT NULL, rsp_ein DOUBLE PRECISION NOT NULL, rsp_win_max DOUBLE PRECISION NOT NULL, rsp_ein_max DOUBLE PRECISION NOT NULL, rsp_wdr_gen DOUBLE PRECISION NOT NULL, rsp_edr_gen DOUBLE PRECISION NOT NULL, rsp_created_by INT NOT NULL, rsp_inserted DATETIME NOT NULL, INDEX IDX_4D8A520A83D3BB28 (activity_act_id), INDEX IDX_4D8A520A935EEA40 (stage_stg_id), INDEX IDX_4D8A520AD26A20E6 (criterion_crt_id), PRIMARY KEY(rsp_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE result_team (rst_id INT AUTO_INCREMENT NOT NULL, activity_act_id INT DEFAULT NULL, stage_stg_id INT DEFAULT NULL, criterion_crt_id INT DEFAULT NULL, team_tea_id INT DEFAULT NULL, rst_type INT DEFAULT NULL, rst_war DOUBLE PRECISION DEFAULT NULL, rst_ear DOUBLE PRECISION DEFAULT NULL, rst_wrr DOUBLE PRECISION DEFAULT NULL, rst_err DOUBLE PRECISION DEFAULT NULL, rst_wsd DOUBLE PRECISION DEFAULT NULL, rst_esd DOUBLE PRECISION DEFAULT NULL, rst_wdr DOUBLE PRECISION DEFAULT NULL, rst_edr DOUBLE PRECISION DEFAULT NULL, rst_wsd_max DOUBLE PRECISION NOT NULL, rst_esd_max DOUBLE PRECISION NOT NULL, rst_win DOUBLE PRECISION NOT NULL, rst_ein DOUBLE PRECISION NOT NULL, rst_win_max DOUBLE PRECISION NOT NULL, rst_ein_max DOUBLE PRECISION NOT NULL, rst_wdr_gen DOUBLE PRECISION NOT NULL, rst_edr_gen DOUBLE PRECISION NOT NULL, rst_created_by INT NOT NULL, rst_inserted DATETIME NOT NULL, INDEX IDX_54DBBD5183D3BB28 (activity_act_id), INDEX IDX_54DBBD51935EEA40 (stage_stg_id), INDEX IDX_54DBBD51D26A20E6 (criterion_crt_id), INDEX IDX_54DBBD511C22DDD4 (team_tea_id), PRIMARY KEY(rst_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (rol_id INT AUTO_INCREMENT NOT NULL, rol_name VARCHAR(10) NOT NULL, rol_created_by INT NOT NULL, rol_inserted DATETIME NOT NULL, PRIMARY KEY(rol_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage (stg_id INT AUTO_INCREMENT NOT NULL, survey_sur_id INT DEFAULT NULL, activity_act_id INT NOT NULL, organization_org_id INT DEFAULT NULL, stg_master_user_id INT DEFAULT NULL, stg_complete TINYINT(1) NOT NULL, stg_name VARCHAR(255) NOT NULL, stg_mode INT NOT NULL, stg_visibility INT NOT NULL, stg_access_link VARCHAR(255) NOT NULL, stg_status INT NOT NULL, stg_desc VARCHAR(255) NOT NULL, stg_progress INT NOT NULL, stg_weight DOUBLE PRECISION NOT NULL, stg_definite_dates TINYINT(1) NOT NULL, stg_dperiod INT NOT NULL, stg_dfrequency VARCHAR(255) NOT NULL, stg_dorigin INT NOT NULL, stg_fperiod INT NOT NULL, stg_ffrequency VARCHAR(255) NOT NULL, stg_forigin INT NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddate DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_dealine_nb_days INT NOT NULL, stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, stg_created_by INT DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_reopened TINYINT(1) NOT NULL, stg_last_reopened DATETIME NOT NULL, stg_unstarted_notif TINYINT(1) NOT NULL, stg_uncompleted_notif TINYINT(1) NOT NULL, stg_unfinished_notif TINYINT(1) NOT NULL, stg_is_finalized TINYINT(1) NOT NULL, stg_deleted DATETIME NOT NULL, stg_gcompleted DATETIME NOT NULL, UNIQUE INDEX UNIQ_C27C93697D7E0D2A (survey_sur_id), INDEX IDX_C27C936983D3BB28 (activity_act_id), INDEX IDX_C27C9369F10DACEE (organization_org_id), INDEX IDX_C27C9369E7127ABC (stg_master_user_id), PRIMARY KEY(stg_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE state (sta_id INT AUTO_INCREMENT NOT NULL, country_cou_id INT NOT NULL, sta_abbr VARCHAR(255) NOT NULL, sta_fullname VARCHAR(255) NOT NULL, sta_name VARCHAR(255) NOT NULL, sta_created_by INT DEFAULT NULL, sta_inserted DATETIME NOT NULL, INDEX IDX_A393D2FBA1599B34 (country_cou_id), PRIMARY KEY(sta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey (sur_id INT AUTO_INCREMENT NOT NULL, stage_stg_id INT DEFAULT NULL, organization_org_id INT DEFAULT NULL, sur_name VARCHAR(45) NOT NULL, sur_created_by INT NOT NULL, sur_inserted DATETIME NOT NULL, sur_state INT NOT NULL, UNIQUE INDEX UNIQ_AD5F9BFC935EEA40 (stage_stg_id), INDEX IDX_AD5F9BFCF10DACEE (organization_org_id), PRIMARY KEY(sur_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_field (sfi_id INT AUTO_INCREMENT NOT NULL, criterion_crt_id INT NOT NULL, survey_sur_id INT NOT NULL, sfi_type VARCHAR(255) NOT NULL, sfi_is_mandatory TINYINT(1) NOT NULL, sfi_title VARCHAR(255) NOT NULL, sfi_position INT NOT NULL, sfi_description VARCHAR(255) NOT NULL, sfi_created_by INT NOT NULL, sfi_inserted DATETIME NOT NULL, sfi_upperbound INT NOT NULL, sfi_lowerbound INT NOT NULL, INDEX IDX_5785B760D26A20E6 (criterion_crt_id), INDEX IDX_5785B7607D7E0D2A (survey_sur_id), PRIMARY KEY(sfi_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_field_parameter (sfp_id INT AUTO_INCREMENT NOT NULL, survey_field_sfi_id INT NOT NULL, sfp_value VARCHAR(255) NOT NULL, sfp_lowerbound DOUBLE PRECISION DEFAULT NULL, sfp_upperbound DOUBLE PRECISION DEFAULT NULL, sfp_step DOUBLE PRECISION DEFAULT NULL, sfp_created_by INT NOT NULL, sfp_inserted DATETIME NOT NULL, INDEX IDX_6740C5AEAFBE78D8 (survey_field_sfi_id), PRIMARY KEY(sfp_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE target (tgt_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, department_dpt_id INT NOT NULL, position_pos_id INT NOT NULL, title_tit_id INT NOT NULL, user_usr_id INT NOT NULL, team_tea_id INT DEFAULT NULL, criterion_name_cna_id INT DEFAULT NULL, criterion_crt_id INT NOT NULL, tgt_sign INT NOT NULL, tgt_value DOUBLE PRECISION NOT NULL, tgt_created_by INT DEFAULT NULL, tgt_inserted DATETIME NOT NULL, INDEX IDX_466F2FFCF10DACEE (organization_org_id), INDEX IDX_466F2FFCB232D839 (department_dpt_id), INDEX IDX_466F2FFCB9E63123 (position_pos_id), INDEX IDX_466F2FFC6AFC588 (title_tit_id), INDEX IDX_466F2FFC693BC8C6 (user_usr_id), INDEX IDX_466F2FFC1C22DDD4 (team_tea_id), UNIQUE INDEX UNIQ_466F2FFCCE87AAFC (criterion_name_cna_id), UNIQUE INDEX UNIQ_466F2FFCD26A20E6 (criterion_crt_id), PRIMARY KEY(tgt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team (tea_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, tea_name VARCHAR(255) NOT NULL, tea_weight_ini DOUBLE PRECISION NOT NULL, tea_picture VARCHAR(10) DEFAULT NULL, tea_created_by INT NOT NULL, tea_inserted DATETIME NOT NULL, tea_deleted DATETIME NOT NULL, INDEX IDX_C4E0A61FF10DACEE (organization_org_id), PRIMARY KEY(tea_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_user (tus_id INT AUTO_INCREMENT NOT NULL, team_tea_id INT NOT NULL, user_usr_id INT DEFAULT NULL, external_user_ext_id_id INT NOT NULL, tus_leader TINYINT(1) NOT NULL, tus_created_by INT NOT NULL, tus_inserted DATETIME NOT NULL, tus_deleted DATETIME DEFAULT NULL, tus_is_deleted TINYINT(1) NOT NULL, INDEX IDX_5C7222321C22DDD4 (team_tea_id), INDEX IDX_5C722232693BC8C6 (user_usr_id), INDEX IDX_5C722232C258E832 (external_user_ext_id_id), PRIMARY KEY(tus_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template (tmp_id INT AUTO_INCREMENT NOT NULL, stage_stg_id INT NOT NULL, criterion_crt_id INT NOT NULL, department_dpt_id INT NOT NULL, organization_org_id INT NOT NULL, original_activity_act_id INT DEFAULT NULL, tmp_name VARCHAR(255) NOT NULL, tmp_created_by INT NOT NULL, tmp_inserted DATETIME NOT NULL, tmp_deleted DATETIME NOT NULL, UNIQUE INDEX UNIQ_97601F83935EEA40 (stage_stg_id), UNIQUE INDEX UNIQ_97601F83D26A20E6 (criterion_crt_id), INDEX IDX_97601F83B232D839 (department_dpt_id), INDEX IDX_97601F83F10DACEE (organization_org_id), INDEX IDX_97601F8341FF5FA2 (original_activity_act_id), PRIMARY KEY(tmp_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_activity (act_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, department_dpt_id INT NOT NULL, recurring_rct_id INT DEFAULT NULL, act_master_usr_id INT DEFAULT NULL, act_simplified TINYINT(1) NOT NULL, act_name VARCHAR(255) NOT NULL, act_visibility VARCHAR(255) NOT NULL, act_objectives VARCHAR(255) NOT NULL, act_created_by INT NOT NULL, act_inserted DATETIME NOT NULL, act_saved DATETIME NOT NULL, INDEX IDX_F3223929F10DACEE (organization_org_id), INDEX IDX_F3223929B232D839 (department_dpt_id), INDEX IDX_F3223929AF5978B5 (recurring_rct_id), INDEX IDX_F32239292267A676 (act_master_usr_id), PRIMARY KEY(act_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_activity_user (a_u_id INT AUTO_INCREMENT NOT NULL, team_tea_id INT NOT NULL, activity_act_id INT NOT NULL, stage_stg_id INT NOT NULL, criterion_crt_id INT DEFAULT NULL, user_usr_id INT NOT NULL, external_user_ext_usr_id INT NOT NULL, a_u_leader TINYINT(1) NOT NULL, a_u_type INT NOT NULL, a_u_m_weight DOUBLE PRECISION NOT NULL, a_u_precomment VARCHAR(10) NOT NULL, a_u_created_by INT DEFAULT NULL, a_u_inserted DATETIME DEFAULT NULL, INDEX IDX_951C7CFC1C22DDD4 (team_tea_id), INDEX IDX_951C7CFC83D3BB28 (activity_act_id), INDEX IDX_951C7CFC935EEA40 (stage_stg_id), INDEX IDX_951C7CFCD26A20E6 (criterion_crt_id), INDEX IDX_951C7CFC693BC8C6 (user_usr_id), INDEX IDX_951C7CFC310C5A5A (external_user_ext_usr_id), PRIMARY KEY(a_u_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_criterion (crt_id INT AUTO_INCREMENT NOT NULL, stage_stg_id INT DEFAULT NULL, criterion_name_cna_id INT DEFAULT NULL, icrt_type INT NOT NULL, crt_name VARCHAR(255) DEFAULT NULL, crt_weight DOUBLE PRECISION NOT NULL, crt_force_comment_compare TINYINT(1) NOT NULL, crt_force_comment_value DOUBLE PRECISION DEFAULT NULL, crt_force_comment_sign VARCHAR(255) DEFAULT NULL, crt_lowerbound DOUBLE PRECISION DEFAULT NULL, crt_upperbound DOUBLE PRECISION DEFAULT NULL, crt_step DOUBLE PRECISION DEFAULT NULL, crt_comment VARCHAR(255) NOT NULL, crt_created_by INT DEFAULT NULL, crt_inserted DATETIME DEFAULT NULL, INDEX IDX_B5D154C7935EEA40 (stage_stg_id), UNIQUE INDEX UNIQ_B5D154C7CE87AAFC (criterion_name_cna_id), PRIMARY KEY(crt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_recurring (rct_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, rct_master_usr_id INT DEFAULT NULL, rct_name VARCHAR(255) NOT NULL, rct_status INT NOT NULL, rct_timeframe VARCHAR(255) NOT NULL, rct_freq INT NOT NULL, rct_gsd_interval INT NOT NULL, rct_gsd_timeframe VARCHAR(255) NOT NULL, rct_ged_interval INT NOT NULL, rct_ged_timeframe VARCHAR(255) NOT NULL, rct_type INT NOT NULL, rct_lowerbound DOUBLE PRECISION NOT NULL, rct_upperbound DOUBLE PRECISION NOT NULL, rct_step DOUBLE PRECISION NOT NULL, rct_open_end TINYINT(1) NOT NULL, rct_startdate DATETIME NOT NULL, rct_enddate DATETIME NOT NULL, rct_same_part TINYINT(1) NOT NULL, rct_created_by INT NOT NULL, rct_inserted DATETIME NOT NULL, rct_deleted DATETIME NOT NULL, INDEX IDX_A53F745BF10DACEE (organization_org_id), INDEX IDX_A53F745B66AC648F (rct_master_usr_id), PRIMARY KEY(rct_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_stage (stg_id INT AUTO_INCREMENT NOT NULL, activity_act_id INT NOT NULL, stg_master_usr_id INT DEFAULT NULL, stg_weight DOUBLE PRECISION NOT NULL, stg_period INT NOT NULL, stg_frequency VARCHAR(255) NOT NULL, stg_startdate DATETIME NOT NULL, stg_enddate DATETIME NOT NULL, stg_gstartdate DATETIME NOT NULL, stg_genddate DATETIME NOT NULL, stg_deadline_nb_days INT NOT NULL, stg_created_by VARCHAR(255) DEFAULT NULL, stg_inserted DATETIME DEFAULT NULL, stg_mode INT DEFAULT NULL, stg_desc VARCHAR(255) NOT NULL, INDEX IDX_F1AA40A683D3BB28 (activity_act_id), INDEX IDX_F1AA40A6AFCB9C11 (stg_master_usr_id), PRIMARY KEY(stg_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE title (tit_id INT AUTO_INCREMENT NOT NULL, organization_org_id INT NOT NULL, weight_wgt_id INT DEFAULT NULL, tit_name VARCHAR(255) NOT NULL, tit_weight_ini DOUBLE PRECISION NOT NULL, tit_created_by INT NOT NULL, tit_inserted DATETIME NOT NULL, tit_deleted DATETIME DEFAULT NULL, INDEX IDX_2B36786BF10DACEE (organization_org_id), INDEX IDX_2B36786B3AF408B7 (weight_wgt_id), PRIMARY KEY(tit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (usr_id INT AUTO_INCREMENT NOT NULL, worker_individual_win_id INT DEFAULT NULL, weight_wgt_id INT NOT NULL, position_pos_id INT DEFAULT NULL, departement_dpt_id INT DEFAULT NULL, title_tit_id INT DEFAULT NULL, organization_org_id INT NOT NULL, usr_int TINYINT(1) NOT NULL, usr_firstname VARCHAR(255) NOT NULL, usr_lastname VARCHAR(255) NOT NULL, usr_username VARCHAR(255) NOT NULL, usr_nickname VARCHAR(255) NOT NULL, usr_birthdate DATETIME NOT NULL, usr_email VARCHAR(255) DEFAULT NULL, usr_password VARCHAR(255) DEFAULT NULL, usr_position_name VARCHAR(255) DEFAULT NULL, usr_picture VARCHAR(255) NOT NULL, usr_token VARCHAR(255) NOT NULL, usr_weight_ini DOUBLE PRECISION NOT NULL, usr_usr_weight_1y DOUBLE PRECISION NOT NULL, usr_weight_2y DOUBLE PRECISION NOT NULL, usr_weight_3y DOUBLE PRECISION NOT NULL, usr_weight_4y DOUBLE PRECISION NOT NULL, usr_weight_5y DOUBLE PRECISION NOT NULL, usr_act_archive_nb_days INT NOT NULL, usr_rm_token VARCHAR(255) NOT NULL, usr_validated DATETIME NOT NULL, usr_enabled_creating_user TINYINT(1) NOT NULL, usr_created_by INT NOT NULL, usr_inserted DATETIME NOT NULL, usr_last_connected DATETIME DEFAULT NULL, usr_deleted DATETIME NOT NULL, role_rol_id INT NOT NULL, usr_superior INT NOT NULL, UNIQUE INDEX UNIQ_8D93D649B1623D83 (worker_individual_win_id), UNIQUE INDEX UNIQ_8D93D6493AF408B7 (weight_wgt_id), INDEX IDX_8D93D649B9E63123 (position_pos_id), INDEX IDX_8D93D6493B6FF20A (departement_dpt_id), INDEX IDX_8D93D6496AFC588 (title_tit_id), INDEX IDX_8D93D649F10DACEE (organization_org_id), PRIMARY KEY(usr_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE weight (wgt_id INT AUTO_INCREMENT NOT NULL, org_id INT NOT NULL, pos_id INT NOT NULL, user_id INT DEFAULT NULL, wgt_interval INT NOT NULL, wgt_titleframe VARCHAR(255) NOT NULL, wgt_value DOUBLE PRECISION DEFAULT NULL, wgt_modified DATETIME DEFAULT NULL, wgt_created_by INT NOT NULL, wgt_inserted DATETIME NOT NULL, wgt_deleted DATETIME DEFAULT NULL, INDEX IDX_7CD5541F4837C1B (org_id), INDEX IDX_7CD554141085FAE (pos_id), UNIQUE INDEX UNIQ_7CD5541A76ED395 (user_id), PRIMARY KEY(wgt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_experience (wex_id INT AUTO_INCREMENT NOT NULL, worker_individual_wid INT NOT NULL, worker_firm_wfi INT NOT NULL, wex_active TINYINT(1) NOT NULL, wex_position VARCHAR(255) NOT NULL, wex_location VARCHAR(255) NOT NULL, wex_startdate DATETIME NOT NULL, wex_enddate DATETIME NOT NULL, wex_created_by INT NOT NULL, wex_inserted DATETIME NOT NULL, INDEX IDX_81AC8070D4203719 (worker_individual_wid), INDEX IDX_81AC80708780C6FF (worker_firm_wfi), PRIMARY KEY(wex_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm (wfi_id INT AUTO_INCREMENT NOT NULL, worker_firm_sector_wfs_id INT NOT NULL, city_cit_id INT NOT NULL, state_sta_id INT NOT NULL, country_cou_id INT NOT NULL, wfi_hq_location VARCHAR(255) NOT NULL, wfi_hq_city VARCHAR(255) NOT NULL, wfi_hq_state VARCHAR(255) NOT NULL, wfi_hq_country VARCHAR(255) NOT NULL, wfi_logo VARCHAR(255) NOT NULL, wfi_website VARCHAR(255) NOT NULL, wfi_creation VARCHAR(255) NOT NULL, wfi_firm_type VARCHAR(255) NOT NULL, wfi_size INT NOT NULL, wfi_nb_lk_followers INT NOT NULL, wfi_nb_lk_employees INT NOT NULL, wfi_active TINYINT(1) NOT NULL, wfi_url VARCHAR(255) NOT NULL, wfi_name VARCHAR(255) NOT NULL, wfi_common_name VARCHAR(255) NOT NULL, wfi_mail_prefix INT NOT NULL, wfi_suffix VARCHAR(255) NOT NULL, wfi_nb_active_exp INT NOT NULL, wfi_created INT NOT NULL, wfi_created_by INT NOT NULL, wfi_inserted DATETIME NOT NULL, UNIQUE INDEX UNIQ_9DC037AC255DBC04 (worker_firm_sector_wfs_id), INDEX IDX_9DC037AC2391AC72 (city_cit_id), INDEX IDX_9DC037AC2378CB28 (state_sta_id), INDEX IDX_9DC037ACA1599B34 (country_cou_id), PRIMARY KEY(wfi_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm_competency (wfc_id INT AUTO_INCREMENT NOT NULL, worker_firm_wfi_id INT NOT NULL, wfc_name VARCHAR(255) NOT NULL, wfc_created_by INT NOT NULL, wfc_inserted DATETIME NOT NULL, INDEX IDX_9E94D7EEA8C102B2 (worker_firm_wfi_id), PRIMARY KEY(wfc_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm_location (wfl_id INT AUTO_INCREMENT NOT NULL, wfl_hq_city VARCHAR(255) NOT NULL, wfl_hq_state VARCHAR(255) NOT NULL, wfl_hq_country VARCHAR(255) NOT NULL, wfl_created_by INT NOT NULL, wfl_inserted DATETIME NOT NULL, PRIMARY KEY(wfl_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_firm_sector (wfs_id INT AUTO_INCREMENT NOT NULL, icon_ico_id INT NOT NULL, wfs_name VARCHAR(255) NOT NULL, wfs_created_by INT NOT NULL, wfs_inserted DATETIME NOT NULL, INDEX IDX_8DDB61C6E2C46BF8 (icon_ico_id), PRIMARY KEY(wfs_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker_individual (win_id INT AUTO_INCREMENT NOT NULL, win_lk_country VARCHAR(10) NOT NULL, win_lk_url VARCHAR(255) NOT NULL, win_lk_full_name VARCHAR(255) NOT NULL, win_lk_male TINYINT(1) NOT NULL, win_created INT NOT NULL, win_firstname VARCHAR(255) NOT NULL, win_lastname VARCHAR(255) NOT NULL, win_email VARCHAR(255) NOT NULL, win_gdpr DATETIME NOT NULL, win_lk_nb_connections INT NOT NULL, win_lk_contacted TINYINT(1) NOT NULL, win_created_by INT NOT NULL, win_inserted DATETIME NOT NULL, PRIMARY KEY(win_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A7EC2F574 FOREIGN KEY (process_id) REFERENCES process (id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A98B600AE FOREIGN KEY (institution_process_id) REFERENCES institution_process (id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A7E1453AC FOREIGN KEY (template_activity_act_id) REFERENCES template_activity (act_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A2267A676 FOREIGN KEY (act_master_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB83D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDBD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25AFBE78D8 FOREIGN KEY (survey_field_sfi_id) REFERENCES survey_field (sfi_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A257D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25661418FB FOREIGN KEY (activity_user_a_u_id) REFERENCES activity_user (a_u_id)');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEAB64340EC6 FOREIGN KEY (apt_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B02342378CB28 FOREIGN KEY (state_sta_id) REFERENCES state (sta_id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234A1599B34 FOREIGN KEY (country_cou_id) REFERENCES country (cou_id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455A12537A8 FOREIGN KEY (client_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455A8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE criterion ADD CONSTRAINT FK_7C822271935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE criterion ADD CONSTRAINT FK_7C822271F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE criterion ADD CONSTRAINT FK_7C822271CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE criterion_group ADD CONSTRAINT FK_863CE5DDF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE criterion_group ADD CONSTRAINT FK_863CE5DDB232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C3E2C46BF8 FOREIGN KEY (icon_ico_id) REFERENCES icon (ico_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C3F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C3B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C33FC278E3 FOREIGN KEY (criterion_group_cgp_id) REFERENCES criterion_group (cgp_id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE4883D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A84F215E7 FOREIGN KEY (masterUser_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18AF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE external_user ADD CONSTRAINT FK_188CB665693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE external_user ADD CONSTRAINT FK_188CB665E9E8A903 FOREIGN KEY (client_cli_id) REFERENCES client (cli_id)');
        $this->addSql('ALTER TABLE generated_image ADD CONSTRAINT FK_6E67FC40CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34517AF523 FOREIGN KEY (activity_user_team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE342463E031 FOREIGN KEY (activity_user_user_usr_id) REFERENCES activity_user (a_u_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE3483D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE04F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE0495B7A1D FOREIGN KEY (process_pro_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE0484F215E7 FOREIGN KEY (masterUser_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE04727ACA70 FOREIGN KEY (parent_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341BB2CC3CA8 FOREIGN KEY (iprocess_inp_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B6E3003B6 FOREIGN KEY (iprocess_stage_stg_id) REFERENCES iprocess_stage (stg_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341BEF264A3A FOREIGN KEY (iprocess_criterion_crt_id) REFERENCES iprocess_criterion (crt_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (id)');
        $this->addSql('ALTER TABLE iprocess_criterion ADD CONSTRAINT FK_57F78ED46E3003B6 FOREIGN KEY (iprocess_stage_stg_id) REFERENCES iprocess_stage (stg_id)');
        $this->addSql('ALTER TABLE iprocess_criterion ADD CONSTRAINT FK_57F78ED4B2CC3CA8 FOREIGN KEY (iprocess_inp_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_criterion ADD CONSTRAINT FK_57F78ED4CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE iprocess_stage ADD CONSTRAINT FK_6864F1B4B2CC3CA8 FOREIGN KEY (iprocess_inp_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_stage ADD CONSTRAINT FK_6864F1B4F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE iprocess_stage ADD CONSTRAINT FK_6864F1B4AFCB9C11 FOREIGN KEY (stg_master_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48B1623D83 FOREIGN KEY (worker_individual_win_id) REFERENCES worker_individual (win_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48A8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC4883D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637CA8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF654B493BD FOREIGN KEY (option_name_ona_id) REFERENCES option_name (ona_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6B9E63123 FOREIGN KEY (position_pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF66AFC588 FOREIGN KEY (title_tit_id) REFERENCES title (tit_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6AF9C58DD FOREIGN KEY (role_rol_id) REFERENCES role (id)');
        $this->addSql('ALTER TABLE otpuser ADD CONSTRAINT FK_2524453FA99EEA35 FOREIGN KEY (otp_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896727ACA70 FOREIGN KEY (parent_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896E2C46BF8 FOREIGN KEY (icon_ico_id) REFERENCES icon (ico_id)');
        $this->addSql('ALTER TABLE process_criterion ADD CONSTRAINT FK_E6CB6099F9E0BF71 FOREIGN KEY (process_stage_stg_id) REFERENCES process_stage (stg_id)');
        $this->addSql('ALTER TABLE process_criterion ADD CONSTRAINT FK_E6CB609995B7A1D FOREIGN KEY (process_pro_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE process_criterion ADD CONSTRAINT FK_E6CB6099CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE process_stage ADD CONSTRAINT FK_9420BE9895B7A1D FOREIGN KEY (process_pro_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE process_stage ADD CONSTRAINT FK_9420BE98F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE process_stage ADD CONSTRAINT FK_9420BE98AFCB9C11 FOREIGN KEY (stg_master_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0FCBCC329 FOREIGN KEY (rnk_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D08D0A8B3D FOREIGN KEY (rnk_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0B5DECA3D FOREIGN KEY (rnk_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D04C14732A FOREIGN KEY (rnk_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D09B266BD9 FOREIGN KEY (rnk_user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B262166DCD468 FOREIGN KEY (rkh_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B2621F4029FC4 FOREIGN KEY (rkh_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B2621B49FDB2C FOREIGN KEY (rkh_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B262163E4206F FOREIGN KEY (rhk_user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD29955B4EB50E FOREIGN KEY (rkt_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD2995547C697E FOREIGN KEY (rkt_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD299510738D20 FOREIGN KEY (rkt_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD29951C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD29954FB5453B FOREIGN KEY (rkt_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE15BD2E465 FOREIGN KEY (rth_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE15199BC43 FOREIGN KEY (rth_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE1CA13A9A1 FOREIGN KEY (rth_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE11C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE11318B4A8 FOREIGN KEY (rth_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE recurring ADD CONSTRAINT FK_6C6C02EDF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE recurring ADD CONSTRAINT FK_6C6C02ED4C86D2E4 FOREIGN KEY (rec_master_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC11383D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113C258E832 FOREIGN KEY (external_user_ext_id_id) REFERENCES external_user (id)');
        $this->addSql('ALTER TABLE result_project ADD CONSTRAINT FK_4D8A520A83D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE result_project ADD CONSTRAINT FK_4D8A520A935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE result_project ADD CONSTRAINT FK_4D8A520AD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD5183D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD51935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD51D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD511C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C93697D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C936983D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369E7127ABC FOREIGN KEY (stg_master_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE state ADD CONSTRAINT FK_A393D2FBA1599B34 FOREIGN KEY (country_cou_id) REFERENCES country (cou_id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFC935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFCF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE survey_field ADD CONSTRAINT FK_5785B760D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE survey_field ADD CONSTRAINT FK_5785B7607D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE survey_field_parameter ADD CONSTRAINT FK_6740C5AEAFBE78D8 FOREIGN KEY (survey_field_sfi_id) REFERENCES survey_field (sfi_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCB232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCB9E63123 FOREIGN KEY (position_pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFC6AFC588 FOREIGN KEY (title_tit_id) REFERENCES title (tit_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFC693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFC1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCCE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C7222321C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232C258E832 FOREIGN KEY (external_user_ext_id_id) REFERENCES external_user (id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F8341FF5FA2 FOREIGN KEY (original_activity_act_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F3223929F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F3223929B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F3223929AF5978B5 FOREIGN KEY (recurring_rct_id) REFERENCES template_recurring (rct_id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F32239292267A676 FOREIGN KEY (act_master_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC83D3BB28 FOREIGN KEY (activity_act_id) REFERENCES template_activity (act_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES template_stage (stg_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFCD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES template_criterion (crt_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (id)');
        $this->addSql('ALTER TABLE template_criterion ADD CONSTRAINT FK_B5D154C7935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES template_stage (stg_id)');
        $this->addSql('ALTER TABLE template_criterion ADD CONSTRAINT FK_B5D154C7CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE template_recurring ADD CONSTRAINT FK_A53F745BF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE template_recurring ADD CONSTRAINT FK_A53F745B66AC648F FOREIGN KEY (rct_master_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE template_stage ADD CONSTRAINT FK_F1AA40A683D3BB28 FOREIGN KEY (activity_act_id) REFERENCES template_activity (act_id)');
        $this->addSql('ALTER TABLE template_stage ADD CONSTRAINT FK_F1AA40A6AFCB9C11 FOREIGN KEY (stg_master_usr_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE title ADD CONSTRAINT FK_2B36786BF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE title ADD CONSTRAINT FK_2B36786B3AF408B7 FOREIGN KEY (weight_wgt_id) REFERENCES weight (wgt_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B1623D83 FOREIGN KEY (worker_individual_win_id) REFERENCES worker_individual (win_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6493AF408B7 FOREIGN KEY (weight_wgt_id) REFERENCES weight (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B9E63123 FOREIGN KEY (position_pos_id) REFERENCES position (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6493B6FF20A FOREIGN KEY (departement_dpt_id) REFERENCES department (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6496AFC588 FOREIGN KEY (title_tit_id) REFERENCES title (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (id)');
        $this->addSql('ALTER TABLE weight ADD CONSTRAINT FK_7CD5541F4837C1B FOREIGN KEY (org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE weight ADD CONSTRAINT FK_7CD554141085FAE FOREIGN KEY (pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE weight ADD CONSTRAINT FK_7CD5541A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE worker_experience ADD CONSTRAINT FK_81AC8070D4203719 FOREIGN KEY (worker_individual_wid) REFERENCES worker_individual (win_id)');
        $this->addSql('ALTER TABLE worker_experience ADD CONSTRAINT FK_81AC80708780C6FF FOREIGN KEY (worker_firm_wfi) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037AC255DBC04 FOREIGN KEY (worker_firm_sector_wfs_id) REFERENCES worker_firm_sector (wfs_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037AC2391AC72 FOREIGN KEY (city_cit_id) REFERENCES city (cit_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037AC2378CB28 FOREIGN KEY (state_sta_id) REFERENCES state (sta_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037ACA1599B34 FOREIGN KEY (country_cou_id) REFERENCES country (cou_id)');
        $this->addSql('ALTER TABLE worker_firm_competency ADD CONSTRAINT FK_9E94D7EEA8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE worker_firm_sector ADD CONSTRAINT FK_8DDB61C6E2C46BF8 FOREIGN KEY (icon_ico_id) REFERENCES icon (ico_id)');
        $this->addSql('ALTER TABLE user_tempo CHANGE username username VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB83D3BB28');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE4883D3BB28');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE3483D3BB28');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC4883D3BB28');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D0FCBCC329');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B262166DCD468');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD29955B4EB50E');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE15BD2E465');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC11383D3BB28');
        $this->addSql('ALTER TABLE result_project DROP FOREIGN KEY FK_4D8A520A83D3BB28');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD5183D3BB28');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C936983D3BB28');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F8341FF5FA2');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25661418FB');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE342463E031');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037AC2391AC72');
        $this->addSql('ALTER TABLE external_user DROP FOREIGN KEY FK_188CB665E9E8A903');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B0234A1599B34');
        $this->addSql('ALTER TABLE state DROP FOREIGN KEY FK_A393D2FBA1599B34');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037ACA1599B34');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDBD26A20E6');
        $this->addSql('ALTER TABLE appreciation DROP FOREIGN KEY FK_5CD4DEAB64340EC6');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE34D26A20E6');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D0B5DECA3D');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B2621B49FDB2C');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD299510738D20');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE1CA13A9A1');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113D26A20E6');
        $this->addSql('ALTER TABLE result_project DROP FOREIGN KEY FK_4D8A520AD26A20E6');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD51D26A20E6');
        $this->addSql('ALTER TABLE survey_field DROP FOREIGN KEY FK_5785B760D26A20E6');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCD26A20E6');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83D26A20E6');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C33FC278E3');
        $this->addSql('ALTER TABLE criterion DROP FOREIGN KEY FK_7C822271CE87AAFC');
        $this->addSql('ALTER TABLE generated_image DROP FOREIGN KEY FK_6E67FC40CE87AAFC');
        $this->addSql('ALTER TABLE iprocess_criterion DROP FOREIGN KEY FK_57F78ED4CE87AAFC');
        $this->addSql('ALTER TABLE process_criterion DROP FOREIGN KEY FK_E6CB6099CE87AAFC');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCCE87AAFC');
        $this->addSql('ALTER TABLE template_criterion DROP FOREIGN KEY FK_B5D154C7CE87AAFC');
        $this->addSql('ALTER TABLE criterion_group DROP FOREIGN KEY FK_863CE5DDB232D839');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C3B232D839');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6B232D839');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5B232D839');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCB232D839');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83B232D839');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F3223929B232D839');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6493B6FF20A');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB310C5A5A');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B310C5A5A');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113C258E832');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C722232C258E832');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC310C5A5A');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C3E2C46BF8');
        $this->addSql('ALTER TABLE process DROP FOREIGN KEY FK_861D1896E2C46BF8');
        $this->addSql('ALTER TABLE worker_firm_sector DROP FOREIGN KEY FK_8DDB61C6E2C46BF8');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A98B600AE');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE04727ACA70');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341BB2CC3CA8');
        $this->addSql('ALTER TABLE iprocess_criterion DROP FOREIGN KEY FK_57F78ED4B2CC3CA8');
        $this->addSql('ALTER TABLE iprocess_stage DROP FOREIGN KEY FK_6864F1B4B2CC3CA8');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341BEF264A3A');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B6E3003B6');
        $this->addSql('ALTER TABLE iprocess_criterion DROP FOREIGN KEY FK_57F78ED46E3003B6');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF654B493BD');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A32C8A3DE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455F10DACEE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455A12537A8');
        $this->addSql('ALTER TABLE criterion DROP FOREIGN KEY FK_7C822271F10DACEE');
        $this->addSql('ALTER TABLE criterion_group DROP FOREIGN KEY FK_863CE5DDF10DACEE');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C3F10DACEE');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48F10DACEE');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18AF10DACEE');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE04F10DACEE');
        $this->addSql('ALTER TABLE iprocess_stage DROP FOREIGN KEY FK_6864F1B4F10DACEE');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48F10DACEE');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6F10DACEE');
        $this->addSql('ALTER TABLE otpuser DROP FOREIGN KEY FK_2524453FA99EEA35');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5F10DACEE');
        $this->addSql('ALTER TABLE process DROP FOREIGN KEY FK_861D1896F10DACEE');
        $this->addSql('ALTER TABLE process_stage DROP FOREIGN KEY FK_9420BE98F10DACEE');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D04C14732A');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD29954FB5453B');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE11318B4A8');
        $this->addSql('ALTER TABLE recurring DROP FOREIGN KEY FK_6C6C02EDF10DACEE');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C9369F10DACEE');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFCF10DACEE');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCF10DACEE');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61FF10DACEE');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83F10DACEE');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F3223929F10DACEE');
        $this->addSql('ALTER TABLE template_recurring DROP FOREIGN KEY FK_A53F745BF10DACEE');
        $this->addSql('ALTER TABLE title DROP FOREIGN KEY FK_2B36786BF10DACEE');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F10DACEE');
        $this->addSql('ALTER TABLE weight DROP FOREIGN KEY FK_7CD5541F4837C1B');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6B9E63123');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCB9E63123');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B9E63123');
        $this->addSql('ALTER TABLE weight DROP FOREIGN KEY FK_7CD554141085FAE');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A7EC2F574');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE0495B7A1D');
        $this->addSql('ALTER TABLE process DROP FOREIGN KEY FK_861D1896727ACA70');
        $this->addSql('ALTER TABLE process_criterion DROP FOREIGN KEY FK_E6CB609995B7A1D');
        $this->addSql('ALTER TABLE process_stage DROP FOREIGN KEY FK_9420BE9895B7A1D');
        $this->addSql('ALTER TABLE process_criterion DROP FOREIGN KEY FK_E6CB6099F9E0BF71');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6AF9C58DD');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB935EEA40');
        $this->addSql('ALTER TABLE criterion DROP FOREIGN KEY FK_7C822271935EEA40');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48935EEA40');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE34935EEA40');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48935EEA40');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D08D0A8B3D');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B2621F4029FC4');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD2995547C697E');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE15199BC43');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113935EEA40');
        $this->addSql('ALTER TABLE result_project DROP FOREIGN KEY FK_4D8A520A935EEA40');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD51935EEA40');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFC935EEA40');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83935EEA40');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B02342378CB28');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037AC2378CB28');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A257D7E0D2A');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C93697D7E0D2A');
        $this->addSql('ALTER TABLE survey_field DROP FOREIGN KEY FK_5785B7607D7E0D2A');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25AFBE78D8');
        $this->addSql('ALTER TABLE survey_field_parameter DROP FOREIGN KEY FK_6740C5AEAFBE78D8');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB1C22DDD4');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE34517AF523');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B1C22DDD4');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD29951C22DDD4');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE11C22DDD4');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD511C22DDD4');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFC1C22DDD4');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C7222321C22DDD4');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC1C22DDD4');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A7E1453AC');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC83D3BB28');
        $this->addSql('ALTER TABLE template_stage DROP FOREIGN KEY FK_F1AA40A683D3BB28');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFCD26A20E6');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F3223929AF5978B5');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC935EEA40');
        $this->addSql('ALTER TABLE template_criterion DROP FOREIGN KEY FK_B5D154C7935EEA40');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF66AFC588');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFC6AFC588');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6496AFC588');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A2267A676');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB693BC8C6');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18A84F215E7');
        $this->addSql('ALTER TABLE external_user DROP FOREIGN KEY FK_188CB665693BC8C6');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE0484F215E7');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B693BC8C6');
        $this->addSql('ALTER TABLE iprocess_stage DROP FOREIGN KEY FK_6864F1B4AFCB9C11');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48693BC8C6');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6693BC8C6');
        $this->addSql('ALTER TABLE process_stage DROP FOREIGN KEY FK_9420BE98AFCB9C11');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D09B266BD9');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B262163E4206F');
        $this->addSql('ALTER TABLE recurring DROP FOREIGN KEY FK_6C6C02ED4C86D2E4');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113693BC8C6');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C9369E7127ABC');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFC693BC8C6');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C722232693BC8C6');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F32239292267A676');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC693BC8C6');
        $this->addSql('ALTER TABLE template_recurring DROP FOREIGN KEY FK_A53F745B66AC648F');
        $this->addSql('ALTER TABLE template_stage DROP FOREIGN KEY FK_F1AA40A6AFCB9C11');
        $this->addSql('ALTER TABLE weight DROP FOREIGN KEY FK_7CD5541A76ED395');
        $this->addSql('ALTER TABLE title DROP FOREIGN KEY FK_2B36786B3AF408B7');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6493AF408B7');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455A8C102B2');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48A8C102B2');
        $this->addSql('ALTER TABLE organization DROP FOREIGN KEY FK_C1EE637CA8C102B2');
        $this->addSql('ALTER TABLE worker_experience DROP FOREIGN KEY FK_81AC80708780C6FF');
        $this->addSql('ALTER TABLE worker_firm_competency DROP FOREIGN KEY FK_9E94D7EEA8C102B2');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037AC255DBC04');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48B1623D83');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B1623D83');
        $this->addSql('ALTER TABLE worker_experience DROP FOREIGN KEY FK_81AC8070D4203719');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_user');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE appreciation');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE criterion');
        $this->addSql('DROP TABLE criterion_group');
        $this->addSql('DROP TABLE criterion_name');
        $this->addSql('DROP TABLE decision');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE external_user');
        $this->addSql('DROP TABLE generated_image');
        $this->addSql('DROP TABLE gpw');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE icon');
        $this->addSql('DROP TABLE institution_process');
        $this->addSql('DROP TABLE iprocess_activity_user');
        $this->addSql('DROP TABLE iprocess_criterion');
        $this->addSql('DROP TABLE iprocess_stage');
        $this->addSql('DROP TABLE lkurl');
        $this->addSql('DROP TABLE mail');
        $this->addSql('DROP TABLE option_name');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_user_option');
        $this->addSql('DROP TABLE otpuser');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE process');
        $this->addSql('DROP TABLE process_criterion');
        $this->addSql('DROP TABLE process_stage');
        $this->addSql('DROP TABLE ranking');
        $this->addSql('DROP TABLE ranking_history');
        $this->addSql('DROP TABLE ranking_team');
        $this->addSql('DROP TABLE ranking_team_history');
        $this->addSql('DROP TABLE record');
        $this->addSql('DROP TABLE recurring');
        $this->addSql('DROP TABLE result');
        $this->addSql('DROP TABLE result_project');
        $this->addSql('DROP TABLE result_team');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE stage');
        $this->addSql('DROP TABLE state');
        $this->addSql('DROP TABLE survey');
        $this->addSql('DROP TABLE survey_field');
        $this->addSql('DROP TABLE survey_field_parameter');
        $this->addSql('DROP TABLE target');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_user');
        $this->addSql('DROP TABLE template');
        $this->addSql('DROP TABLE template_activity');
        $this->addSql('DROP TABLE template_activity_user');
        $this->addSql('DROP TABLE template_criterion');
        $this->addSql('DROP TABLE template_recurring');
        $this->addSql('DROP TABLE template_stage');
        $this->addSql('DROP TABLE title');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE weight');
        $this->addSql('DROP TABLE worker_experience');
        $this->addSql('DROP TABLE worker_firm');
        $this->addSql('DROP TABLE worker_firm_competency');
        $this->addSql('DROP TABLE worker_firm_location');
        $this->addSql('DROP TABLE worker_firm_sector');
        $this->addSql('DROP TABLE worker_individual');
        $this->addSql('ALTER TABLE user_tempo CHANGE username username VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
    }
}
