<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200818123805 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A98B600AE FOREIGN KEY (institution_process_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A7E1453AC FOREIGN KEY (template_activity_act_id) REFERENCES template_activity (act_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A2267A676 FOREIGN KEY (act_master_usr_id) REFERENCES user (usr_id)');
        $this->addSql('CREATE INDEX IDX_AC74095A7E1453AC ON activity (template_activity_act_id)');
        $this->addSql('CREATE INDEX IDX_AC74095A2267A676 ON activity (act_master_usr_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB83D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDBD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB7D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE activity_user ADD CONSTRAINT FK_8E570DDB310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (ext_id)');
        $this->addSql('CREATE INDEX IDX_8E570DDB7D7E0D2A ON activity_user (survey_sur_id)');
        $this->addSql('ALTER TABLE answer ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25AFBE78D8 FOREIGN KEY (survey_field_sfi_id) REFERENCES survey_field (sfi_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A257D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25661418FB FOREIGN KEY (activity_user_a_u_id) REFERENCES activity_user (a_u_id)');
        $this->addSql('ALTER TABLE appreciation ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEAB64340EC6 FOREIGN KEY (apt_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE city ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B02342378CB28 FOREIGN KEY (state_sta_id) REFERENCES state (sta_id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234A1599B34 FOREIGN KEY (country_cou_id) REFERENCES country (cou_id)');
        $this->addSql('ALTER TABLE client ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455A12537A8 FOREIGN KEY (client_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455A8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE contact ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE country ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE criterion ADD CONSTRAINT FK_7C822271935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE criterion ADD CONSTRAINT FK_7C822271F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE criterion ADD CONSTRAINT FK_7C822271CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE criterion_group ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE criterion_group ADD CONSTRAINT FK_863CE5DDF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE criterion_group ADD CONSTRAINT FK_863CE5DDB232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C3E2C46BF8 FOREIGN KEY (icon_ico_id) REFERENCES icon (ico_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C3F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C3B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE criterion_name ADD CONSTRAINT FK_ACB459C33FC278E3 FOREIGN KEY (criterion_group_cgp_id) REFERENCES criterion_group (cgp_id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE4883D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE department ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A84F215E7 FOREIGN KEY (masterUser_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18AF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE external_user ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE external_user ADD CONSTRAINT FK_188CB665693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE external_user ADD CONSTRAINT FK_188CB665E9E8A903 FOREIGN KEY (client_cli_id) REFERENCES client (cli_id)');
        $this->addSql('ALTER TABLE generated_image ADD gim_cid INT DEFAULT NULL, ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE generated_image ADD CONSTRAINT FK_6E67FC40CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE gpw ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE grade ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34517AF523 FOREIGN KEY (activity_user_team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE342463E031 FOREIGN KEY (activity_user_user_usr_id) REFERENCES activity_user (a_u_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE3483D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE icon ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE institution_process DROP INDEX UNIQ_E2E3EE04727ACA70, ADD INDEX IDX_E2E3EE04727ACA70 (parent_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE04F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE0495B7A1D FOREIGN KEY (process_pro_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE0484F215E7 FOREIGN KEY (masterUser_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE institution_process ADD CONSTRAINT FK_E2E3EE04727ACA70 FOREIGN KEY (parent_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL, CHANGE external_user_ext_usr_id external_useR_ext_usr_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341BB2CC3CA8 FOREIGN KEY (iprocess_inp_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B6E3003B6 FOREIGN KEY (iprocess_stage_stg_id) REFERENCES iprocess_stage (stg_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341BEF264A3A FOREIGN KEY (iprocess_criterion_crt_id) REFERENCES iprocess_criterion (crt_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user ADD CONSTRAINT FK_DA74341B293D81A2 FOREIGN KEY (external_useR_ext_usr_id) REFERENCES external_user (ext_id)');
        $this->addSql('ALTER TABLE iprocess_activity_user RENAME INDEX idx_da74341b310c5a5a TO IDX_DA74341B293D81A2');
        $this->addSql('ALTER TABLE iprocess_criterion ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE iprocess_criterion ADD CONSTRAINT FK_57F78ED46E3003B6 FOREIGN KEY (iprocess_stage_stg_id) REFERENCES iprocess_stage (stg_id)');
        $this->addSql('ALTER TABLE iprocess_criterion ADD CONSTRAINT FK_57F78ED4B2CC3CA8 FOREIGN KEY (iprocess_inp_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_criterion ADD CONSTRAINT FK_57F78ED4CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('DROP INDEX IDX_6864F1B4AFCB9C11 ON iprocess_stage');
        $this->addSql('ALTER TABLE iprocess_stage ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL, CHANGE stg_master_usr_id stg_master_user_id INT NOT NULL');
        $this->addSql('ALTER TABLE iprocess_stage ADD CONSTRAINT FK_6864F1B4B2CC3CA8 FOREIGN KEY (iprocess_inp_id) REFERENCES institution_process (inp_id)');
        $this->addSql('ALTER TABLE iprocess_stage ADD CONSTRAINT FK_6864F1B4F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE iprocess_stage ADD CONSTRAINT FK_6864F1B4E7127ABC FOREIGN KEY (stg_master_user_id) REFERENCES user (usr_id)');
        $this->addSql('CREATE INDEX IDX_6864F1B4E7127ABC ON iprocess_stage (stg_master_user_id)');
        $this->addSql('ALTER TABLE lkurl ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE mail ADD mail_type VARCHAR(255) NOT NULL, ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48B1623D83 FOREIGN KEY (worker_individual_win_id) REFERENCES worker_individual (win_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48A8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC4883D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE mail ADD CONSTRAINT FK_5126AC48935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE option_name CHANGE ona_created_by ona_created_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE organization CHANGE org_commname org_commname VARCHAR(255) NOT NULL, CHANGE org_oth_language org_oth_language VARCHAR(255) NOT NULL, CHANGE org_created_by org_created_by INT NOT NULL, CHANGE org_inserted org_inserted DATETIME NOT NULL, CHANGE org_validated org_validated DATETIME NOT NULL, CHANGE org_expired org_expired DATETIME NOT NULL, CHANGE org_testing_reminder_sent org_testing_reminder_sent TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637CA8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF654B493BD FOREIGN KEY (option_name_ona_id) REFERENCES option_name (ona_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6B9E63123 FOREIGN KEY (position_pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF66AFC588 FOREIGN KEY (title_tit_id) REFERENCES title (tit_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE organization_user_option ADD CONSTRAINT FK_F88BFF6AF9C58DD FOREIGN KEY (role_rol_id) REFERENCES role (rol_id)');
        $this->addSql('ALTER TABLE otpuser ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE otpuser ADD CONSTRAINT FK_2524453FA99EEA35 FOREIGN KEY (otp_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE position ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE process CHANGE pro_approvable $pro_approvable TINYINT(1) NOT NULL, CHANGE pro_created_by $pro_createdBy INT NOT NULL, CHANGE pro_inserted $pro_inserted DATETIME NOT NULL, CHANGE pro_deleted $pro_deleted DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896727ACA70 FOREIGN KEY (parent_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896E2C46BF8 FOREIGN KEY (icon_ico_id) REFERENCES icon (ico_id)');
        $this->addSql('ALTER TABLE process_criterion ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE process_criterion ADD CONSTRAINT FK_E6CB6099F9E0BF71 FOREIGN KEY (process_stage_stg_id) REFERENCES process_stage (stg_id)');
        $this->addSql('ALTER TABLE process_criterion ADD CONSTRAINT FK_E6CB609995B7A1D FOREIGN KEY (process_pro_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE process_criterion ADD CONSTRAINT FK_E6CB6099CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE process_stage ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE process_stage ADD CONSTRAINT FK_9420BE9895B7A1D FOREIGN KEY (process_pro_id) REFERENCES process (pro_id)');
        $this->addSql('ALTER TABLE process_stage ADD CONSTRAINT FK_9420BE98F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE process_stage ADD CONSTRAINT FK_9420BE98AFCB9C11 FOREIGN KEY (stg_master_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0FCBCC329 FOREIGN KEY (rnk_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D08D0A8B3D FOREIGN KEY (rnk_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0B5DECA3D FOREIGN KEY (rnk_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D04C14732A FOREIGN KEY (rnk_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D09B266BD9 FOREIGN KEY (rnk_user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('DROP INDEX IDX_2F6B262163E4206F ON ranking_history');
        $this->addSql('ALTER TABLE ranking_history ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL, CHANGE rhk_user_usr_id rkh_user_usr_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B262166DCD468 FOREIGN KEY (rkh_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B2621F4029FC4 FOREIGN KEY (rkh_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B2621B49FDB2C FOREIGN KEY (rkh_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking_history ADD CONSTRAINT FK_2F6B2621A24F697A FOREIGN KEY (rkh_user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('CREATE INDEX IDX_2F6B2621A24F697A ON ranking_history (rkh_user_usr_id)');
        $this->addSql('ALTER TABLE ranking_team ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD29955B4EB50E FOREIGN KEY (rkt_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD2995547C697E FOREIGN KEY (rkt_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD299510738D20 FOREIGN KEY (rkt_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD29951C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE ranking_team ADD CONSTRAINT FK_6DDD29954FB5453B FOREIGN KEY (rkt_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE15BD2E465 FOREIGN KEY (rth_activity) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE15199BC43 FOREIGN KEY (rth_stage) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE1CA13A9A1 FOREIGN KEY (rth_criterion) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE11C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE ranking_team_history ADD CONSTRAINT FK_A1B5EBE11318B4A8 FOREIGN KEY (rth_organization) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE recurring ADD CONSTRAINT FK_6C6C02EDF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE recurring ADD CONSTRAINT FK_6C6C02ED4C86D2E4 FOREIGN KEY (rec_master_user_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC11383D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE result ADD CONSTRAINT FK_136AC113310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (ext_id)');
        $this->addSql('ALTER TABLE result RENAME INDEX idx_136ac113c258e832 TO IDX_136AC113310C5A5A');
        $this->addSql('ALTER TABLE result_project ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE result_project ADD CONSTRAINT FK_4D8A520A83D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE result_project ADD CONSTRAINT FK_4D8A520A935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE result_project ADD CONSTRAINT FK_4D8A520AD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE result_team ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD5183D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD51935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD51D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE result_team ADD CONSTRAINT FK_54DBBD511C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE role CHANGE rol_name rol_name VARCHAR(10) NOT NULL');
        $this->addSql('DROP INDEX IDX_C27C9369E7127ABC ON stage');
        $this->addSql('ALTER TABLE stage ADD usr_id INT DEFAULT NULL, ADD $stg_desc VARCHAR(255) NOT NULL, ADD $stg_definite_dates TINYINT(1) NOT NULL, ADD $stg_dperiod INT NOT NULL, ADD $stg_dfrequency VARCHAR(255) NOT NULL, ADD $stg_dorigin INT NOT NULL, ADD $stg_enddate DATETIME NOT NULL, ADD  $stg_genddate DATETIME NOT NULL, ADD $stg_createdBy INT DEFAULT NULL, ADD $stg_reopened TINYINT(1) NOT NULL, ADD $stg_last_reopened DATETIME NOT NULL, ADD $stg_unstarted_notif TINYINT(1) NOT NULL, ADD $stg_uncompleted_notif TINYINT(1) NOT NULL, ADD $stg_unfinished_notif TINYINT(1) NOT NULL, ADD $stg_isFinalized TINYINT(1) NOT NULL, ADD $stg_deleted DATETIME NOT NULL, ADD $stg_gcompleted DATETIME NOT NULL, DROP stg_master_user_id, DROP stg_desc, DROP stg_definite_dates, DROP stg_dperiod, DROP stg_dfrequency, DROP stg_dorigin, DROP stg_enddate, DROP stg_genddate, DROP stg_created_by, DROP stg_reopened, DROP stg_last_reopened, DROP stg_unstarted_notif, DROP stg_uncompleted_notif, DROP stg_unfinished_notif, DROP stg_is_finalized, DROP stg_deleted, DROP stg_gcompleted, CHANGE stg_deadline_mail_sent $stg_deadline_mailSent TINYINT(1) DEFAULT NULL, CHANGE stg_inserted $stg_inserted DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C93697D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C936983D3BB28 FOREIGN KEY (activity_act_id) REFERENCES activity (act_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369C69D3FB FOREIGN KEY (usr_id) REFERENCES user (usr_id)');
        $this->addSql('CREATE INDEX IDX_C27C9369C69D3FB ON stage (usr_id)');
        $this->addSql('ALTER TABLE state ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE state ADD CONSTRAINT FK_A393D2FBA1599B34 FOREIGN KEY (country_cou_id) REFERENCES country (cou_id)');
        $this->addSql('ALTER TABLE survey ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFC935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFCF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE survey_field ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey_field ADD CONSTRAINT FK_5785B760D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE survey_field ADD CONSTRAINT FK_5785B7607D7E0D2A FOREIGN KEY (survey_sur_id) REFERENCES survey (sur_id)');
        $this->addSql('ALTER TABLE survey_field_parameter ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE survey_field_parameter ADD CONSTRAINT FK_6740C5AEAFBE78D8 FOREIGN KEY (survey_field_sfi_id) REFERENCES survey_field (sfi_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCB232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCB9E63123 FOREIGN KEY (position_pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFC6AFC588 FOREIGN KEY (title_tit_id) REFERENCES title (tit_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFC693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFC1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCCE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE target ADD CONSTRAINT FK_466F2FFCD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE team ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C7222321C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE team_user ADD CONSTRAINT FK_5C722232310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (ext_id)');
        $this->addSql('ALTER TABLE team_user RENAME INDEX idx_5c722232c258e832 TO IDX_5C722232310C5A5A');
        $this->addSql('DROP INDEX IDX_97601F8341FF5FA2 ON template');
        $this->addSql('ALTER TABLE template ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL, CHANGE original_activity_act_id original_activity_act INT DEFAULT NULL');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES stage (stg_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83D26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES criterion (crt_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83699ADF0 FOREIGN KEY (original_activity_act) REFERENCES activity (act_id)');
        $this->addSql('CREATE INDEX IDX_97601F83699ADF0 ON template (original_activity_act)');
        $this->addSql('DROP INDEX IDX_F32239292267A676 ON template_activity');
        $this->addSql('ALTER TABLE template_activity ADD act_magnitude INT NOT NULL, ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL, CHANGE act_master_usr_id act_master_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F3223929F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F3223929B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F3223929AF5978B5 FOREIGN KEY (recurring_rct_id) REFERENCES template_recurring (rct_id)');
        $this->addSql('ALTER TABLE template_activity ADD CONSTRAINT FK_F32239297083C8AA FOREIGN KEY (act_master_id) REFERENCES user (usr_id)');
        $this->addSql('CREATE INDEX IDX_F32239297083C8AA ON template_activity (act_master_id)');
        $this->addSql('ALTER TABLE template_activity_user CHANGE external_user_ext_usr_id external_user_ext_usr_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC1C22DDD4 FOREIGN KEY (team_tea_id) REFERENCES team (tea_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC83D3BB28 FOREIGN KEY (activity_act_id) REFERENCES template_activity (act_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES template_stage (stg_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFCD26A20E6 FOREIGN KEY (criterion_crt_id) REFERENCES template_criterion (crt_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE template_activity_user ADD CONSTRAINT FK_951C7CFC310C5A5A FOREIGN KEY (external_user_ext_usr_id) REFERENCES external_user (ext_id)');
        $this->addSql('ALTER TABLE template_criterion ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE template_criterion ADD CONSTRAINT FK_B5D154C7935EEA40 FOREIGN KEY (stage_stg_id) REFERENCES template_stage (stg_id)');
        $this->addSql('ALTER TABLE template_criterion ADD CONSTRAINT FK_B5D154C7CE87AAFC FOREIGN KEY (criterion_name_cna_id) REFERENCES criterion_name (cna_id)');
        $this->addSql('ALTER TABLE template_recurring ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE template_recurring ADD CONSTRAINT FK_A53F745BF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE template_recurring ADD CONSTRAINT FK_A53F745B66AC648F FOREIGN KEY (rct_master_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE template_stage ADD stg_name VARCHAR(255) NOT NULL, ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE template_stage ADD CONSTRAINT FK_F1AA40A683D3BB28 FOREIGN KEY (activity_act_id) REFERENCES template_activity (act_id)');
        $this->addSql('ALTER TABLE template_stage ADD CONSTRAINT FK_F1AA40A6AFCB9C11 FOREIGN KEY (stg_master_usr_id) REFERENCES user (usr_id)');
        $this->addSql('ALTER TABLE title ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE title ADD CONSTRAINT FK_2B36786BF10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE title ADD CONSTRAINT FK_2B36786B3AF408B7 FOREIGN KEY (weight_wgt_id) REFERENCES weight (wgt_id)');
        $this->addSql('ALTER TABLE user CHANGE weight_wgt_id weight_wgt_id INT NOT NULL, CHANGE organization_org_id organization_org_id INT NOT NULL, CHANGE usr_picture usr_picture VARCHAR(255) NOT NULL, CHANGE usr_token usr_token VARCHAR(255) NOT NULL, CHANGE usr_weight_ini usr_weight_ini DOUBLE PRECISION NOT NULL, CHANGE usr_rm_token usr_rm_token VARCHAR(255) NOT NULL, CHANGE usr_validated usr_validated DATETIME NOT NULL, CHANGE usr_enabled_creating_user usr_enabled_creating_user TINYINT(1) NOT NULL, CHANGE usr_created_by usr_created_by INT NOT NULL, CHANGE usr_inserted usr_inserted DATETIME NOT NULL, CHANGE usr_deleted usr_deleted DATETIME NOT NULL, CHANGE usr_superior usr_superior INT NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B1623D83 FOREIGN KEY (worker_individual_win_id) REFERENCES worker_individual (win_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6493AF408B7 FOREIGN KEY (weight_wgt_id) REFERENCES weight (wgt_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B9E63123 FOREIGN KEY (position_pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B232D839 FOREIGN KEY (department_dpt_id) REFERENCES department (dpt_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6496AFC588 FOREIGN KEY (title_tit_id) REFERENCES title (tit_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649F10DACEE FOREIGN KEY (organization_org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE user RENAME INDEX idx_8d93d6493b6ff20a TO IDX_8D93D649B232D839');
        $this->addSql('ALTER TABLE user_tempo CHANGE username username VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX UNIQ_7CD5541A76ED395 ON weight');
        $this->addSql('ALTER TABLE weight ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL, CHANGE user_id user_usr_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE weight ADD CONSTRAINT FK_7CD5541F4837C1B FOREIGN KEY (org_id) REFERENCES organization (org_id)');
        $this->addSql('ALTER TABLE weight ADD CONSTRAINT FK_7CD554141085FAE FOREIGN KEY (pos_id) REFERENCES position (pos_id)');
        $this->addSql('ALTER TABLE weight ADD CONSTRAINT FK_7CD5541693BC8C6 FOREIGN KEY (user_usr_id) REFERENCES user (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7CD5541693BC8C6 ON weight (user_usr_id)');
        $this->addSql('ALTER TABLE worker_experience ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE worker_experience ADD CONSTRAINT FK_81AC8070D4203719 FOREIGN KEY (worker_individual_wid) REFERENCES worker_individual (win_id)');
        $this->addSql('ALTER TABLE worker_experience ADD CONSTRAINT FK_81AC80708780C6FF FOREIGN KEY (worker_firm_wfi) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE worker_firm ADD wfi_creation_date DATETIME NOT NULL, ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037AC255DBC04 FOREIGN KEY (worker_firm_sector_wfs_id) REFERENCES worker_firm_sector (wfs_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037AC2391AC72 FOREIGN KEY (city_cit_id) REFERENCES city (cit_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037AC2378CB28 FOREIGN KEY (state_sta_id) REFERENCES state (sta_id)');
        $this->addSql('ALTER TABLE worker_firm ADD CONSTRAINT FK_9DC037ACA1599B34 FOREIGN KEY (country_cou_id) REFERENCES country (cou_id)');
        $this->addSql('ALTER TABLE worker_firm_competency ADD createdBy INT NOT NULL, ADD inserted DATETIME NOT NULL');
        $this->addSql('ALTER TABLE worker_firm_competency ADD CONSTRAINT FK_9E94D7EEA8C102B2 FOREIGN KEY (worker_firm_wfi_id) REFERENCES worker_firm (wfi_id)');
        $this->addSql('ALTER TABLE worker_firm_sector ADD CONSTRAINT FK_8DDB61C6E2C46BF8 FOREIGN KEY (icon_ico_id) REFERENCES icon (ico_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A98B600AE');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095AF10DACEE');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A7E1453AC');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095A2267A676');
        $this->addSql('DROP INDEX IDX_AC74095A7E1453AC ON activity');
        $this->addSql('DROP INDEX IDX_AC74095A2267A676 ON activity');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB1C22DDD4');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB83D3BB28');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB935EEA40');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDBD26A20E6');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB7D7E0D2A');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB693BC8C6');
        $this->addSql('ALTER TABLE activity_user DROP FOREIGN KEY FK_8E570DDB310C5A5A');
        $this->addSql('DROP INDEX IDX_8E570DDB7D7E0D2A ON activity_user');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25AFBE78D8');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A257D7E0D2A');
        $this->addSql('ALTER TABLE answer DROP FOREIGN KEY FK_DADD4A25661418FB');
        $this->addSql('ALTER TABLE answer DROP inserted');
        $this->addSql('ALTER TABLE appreciation DROP FOREIGN KEY FK_5CD4DEAB64340EC6');
        $this->addSql('ALTER TABLE appreciation DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B02342378CB28');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B0234A1599B34');
        $this->addSql('ALTER TABLE city DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455F10DACEE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455A12537A8');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455A8C102B2');
        $this->addSql('ALTER TABLE client DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE contact DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE country DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE criterion DROP FOREIGN KEY FK_7C822271935EEA40');
        $this->addSql('ALTER TABLE criterion DROP FOREIGN KEY FK_7C822271F10DACEE');
        $this->addSql('ALTER TABLE criterion DROP FOREIGN KEY FK_7C822271CE87AAFC');
        $this->addSql('ALTER TABLE criterion_group DROP FOREIGN KEY FK_863CE5DDF10DACEE');
        $this->addSql('ALTER TABLE criterion_group DROP FOREIGN KEY FK_863CE5DDB232D839');
        $this->addSql('ALTER TABLE criterion_group DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C3E2C46BF8');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C3F10DACEE');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C3B232D839');
        $this->addSql('ALTER TABLE criterion_name DROP FOREIGN KEY FK_ACB459C33FC278E3');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48F10DACEE');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE4883D3BB28');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48935EEA40');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18A84F215E7');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18AF10DACEE');
        $this->addSql('ALTER TABLE department DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE external_user DROP FOREIGN KEY FK_188CB665693BC8C6');
        $this->addSql('ALTER TABLE external_user DROP FOREIGN KEY FK_188CB665E9E8A903');
        $this->addSql('ALTER TABLE external_user DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE generated_image DROP FOREIGN KEY FK_6E67FC40CE87AAFC');
        $this->addSql('ALTER TABLE generated_image DROP gim_cid, DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE gpw DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE34517AF523');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE342463E031');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE3483D3BB28');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE34D26A20E6');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE34935EEA40');
        $this->addSql('ALTER TABLE grade DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE icon DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE institution_process DROP INDEX IDX_E2E3EE04727ACA70, ADD UNIQUE INDEX UNIQ_E2E3EE04727ACA70 (parent_id)');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE04F10DACEE');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE0495B7A1D');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE0484F215E7');
        $this->addSql('ALTER TABLE institution_process DROP FOREIGN KEY FK_E2E3EE04727ACA70');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B1C22DDD4');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341BB2CC3CA8');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B6E3003B6');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341BEF264A3A');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B693BC8C6');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP FOREIGN KEY FK_DA74341B293D81A2');
        $this->addSql('ALTER TABLE iprocess_activity_user DROP createdBy, DROP inserted, CHANGE external_useR_ext_usr_id external_user_ext_usr_id INT NOT NULL');
        $this->addSql('ALTER TABLE iprocess_activity_user RENAME INDEX idx_da74341b293d81a2 TO IDX_DA74341B310C5A5A');
        $this->addSql('ALTER TABLE iprocess_criterion DROP FOREIGN KEY FK_57F78ED46E3003B6');
        $this->addSql('ALTER TABLE iprocess_criterion DROP FOREIGN KEY FK_57F78ED4B2CC3CA8');
        $this->addSql('ALTER TABLE iprocess_criterion DROP FOREIGN KEY FK_57F78ED4CE87AAFC');
        $this->addSql('ALTER TABLE iprocess_criterion DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE iprocess_stage DROP FOREIGN KEY FK_6864F1B4B2CC3CA8');
        $this->addSql('ALTER TABLE iprocess_stage DROP FOREIGN KEY FK_6864F1B4F10DACEE');
        $this->addSql('ALTER TABLE iprocess_stage DROP FOREIGN KEY FK_6864F1B4E7127ABC');
        $this->addSql('DROP INDEX IDX_6864F1B4E7127ABC ON iprocess_stage');
        $this->addSql('ALTER TABLE iprocess_stage ADD stg_master_usr_id INT NOT NULL, DROP stg_master_user_id, DROP createdBy, DROP inserted');
        $this->addSql('CREATE INDEX IDX_6864F1B4AFCB9C11 ON iprocess_stage (stg_master_usr_id)');
        $this->addSql('ALTER TABLE lkurl DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48693BC8C6');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48B1623D83');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48F10DACEE');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48A8C102B2');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC4883D3BB28');
        $this->addSql('ALTER TABLE mail DROP FOREIGN KEY FK_5126AC48935EEA40');
        $this->addSql('ALTER TABLE mail DROP mail_type, DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE option_name CHANGE ona_created_by ona_created_by INT NOT NULL');
        $this->addSql('ALTER TABLE organization DROP FOREIGN KEY FK_C1EE637CA8C102B2');
        $this->addSql('ALTER TABLE organization CHANGE org_commname org_commname VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE org_oth_language org_oth_language VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE org_created_by org_created_by INT DEFAULT NULL, CHANGE org_inserted org_inserted DATETIME DEFAULT NULL, CHANGE org_validated org_validated DATETIME DEFAULT NULL, CHANGE org_expired org_expired DATETIME DEFAULT NULL, CHANGE org_testing_reminder_sent org_testing_reminder_sent TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF654B493BD');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6F10DACEE');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6B232D839');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6B9E63123');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF66AFC588');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6693BC8C6');
        $this->addSql('ALTER TABLE organization_user_option DROP FOREIGN KEY FK_F88BFF6AF9C58DD');
        $this->addSql('ALTER TABLE otpuser DROP FOREIGN KEY FK_2524453FA99EEA35');
        $this->addSql('ALTER TABLE otpuser DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5F10DACEE');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5B232D839');
        $this->addSql('ALTER TABLE position DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE process DROP FOREIGN KEY FK_861D1896F10DACEE');
        $this->addSql('ALTER TABLE process DROP FOREIGN KEY FK_861D1896727ACA70');
        $this->addSql('ALTER TABLE process DROP FOREIGN KEY FK_861D1896E2C46BF8');
        $this->addSql('ALTER TABLE process CHANGE $pro_approvable pro_approvable TINYINT(1) NOT NULL, CHANGE $pro_createdby pro_created_by INT NOT NULL, CHANGE $pro_inserted pro_inserted DATETIME NOT NULL, CHANGE $pro_deleted pro_deleted DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE process_criterion DROP FOREIGN KEY FK_E6CB6099F9E0BF71');
        $this->addSql('ALTER TABLE process_criterion DROP FOREIGN KEY FK_E6CB609995B7A1D');
        $this->addSql('ALTER TABLE process_criterion DROP FOREIGN KEY FK_E6CB6099CE87AAFC');
        $this->addSql('ALTER TABLE process_criterion DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE process_stage DROP FOREIGN KEY FK_9420BE9895B7A1D');
        $this->addSql('ALTER TABLE process_stage DROP FOREIGN KEY FK_9420BE98F10DACEE');
        $this->addSql('ALTER TABLE process_stage DROP FOREIGN KEY FK_9420BE98AFCB9C11');
        $this->addSql('ALTER TABLE process_stage DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D0FCBCC329');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D08D0A8B3D');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D0B5DECA3D');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D04C14732A');
        $this->addSql('ALTER TABLE ranking DROP FOREIGN KEY FK_80B839D09B266BD9');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B262166DCD468');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B2621F4029FC4');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B2621B49FDB2C');
        $this->addSql('ALTER TABLE ranking_history DROP FOREIGN KEY FK_2F6B2621A24F697A');
        $this->addSql('DROP INDEX IDX_2F6B2621A24F697A ON ranking_history');
        $this->addSql('ALTER TABLE ranking_history DROP createdBy, DROP inserted, CHANGE rkh_user_usr_id rhk_user_usr_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_2F6B262163E4206F ON ranking_history (rhk_user_usr_id)');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD29955B4EB50E');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD2995547C697E');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD299510738D20');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD29951C22DDD4');
        $this->addSql('ALTER TABLE ranking_team DROP FOREIGN KEY FK_6DDD29954FB5453B');
        $this->addSql('ALTER TABLE ranking_team DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE15BD2E465');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE15199BC43');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE1CA13A9A1');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE11C22DDD4');
        $this->addSql('ALTER TABLE ranking_team_history DROP FOREIGN KEY FK_A1B5EBE11318B4A8');
        $this->addSql('ALTER TABLE ranking_team_history DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE recurring DROP FOREIGN KEY FK_6C6C02EDF10DACEE');
        $this->addSql('ALTER TABLE recurring DROP FOREIGN KEY FK_6C6C02ED4C86D2E4');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC11383D3BB28');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113935EEA40');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113D26A20E6');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113693BC8C6');
        $this->addSql('ALTER TABLE result DROP FOREIGN KEY FK_136AC113310C5A5A');
        $this->addSql('ALTER TABLE result RENAME INDEX idx_136ac113310c5a5a TO IDX_136AC113C258E832');
        $this->addSql('ALTER TABLE result_project DROP FOREIGN KEY FK_4D8A520A83D3BB28');
        $this->addSql('ALTER TABLE result_project DROP FOREIGN KEY FK_4D8A520A935EEA40');
        $this->addSql('ALTER TABLE result_project DROP FOREIGN KEY FK_4D8A520AD26A20E6');
        $this->addSql('ALTER TABLE result_project DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD5183D3BB28');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD51935EEA40');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD51D26A20E6');
        $this->addSql('ALTER TABLE result_team DROP FOREIGN KEY FK_54DBBD511C22DDD4');
        $this->addSql('ALTER TABLE result_team DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE role CHANGE rol_name rol_name CHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C93697D7E0D2A');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C936983D3BB28');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C9369F10DACEE');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C9369C69D3FB');
        $this->addSql('DROP INDEX IDX_C27C9369C69D3FB ON stage');
        $this->addSql('ALTER TABLE stage ADD stg_master_user_id INT DEFAULT NULL, ADD stg_desc VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ADD stg_definite_dates TINYINT(1) NOT NULL, ADD stg_dperiod INT NOT NULL, ADD stg_dfrequency VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ADD stg_dorigin INT NOT NULL, ADD stg_enddate DATETIME NOT NULL, ADD stg_genddate DATETIME NOT NULL, ADD stg_created_by INT DEFAULT NULL, ADD stg_reopened TINYINT(1) NOT NULL, ADD stg_last_reopened DATETIME NOT NULL, ADD stg_unstarted_notif TINYINT(1) NOT NULL, ADD stg_uncompleted_notif TINYINT(1) NOT NULL, ADD stg_unfinished_notif TINYINT(1) NOT NULL, ADD stg_is_finalized TINYINT(1) NOT NULL, ADD stg_deleted DATETIME NOT NULL, ADD stg_gcompleted DATETIME NOT NULL, DROP usr_id, DROP $stg_desc, DROP $stg_definite_dates, DROP $stg_dperiod, DROP $stg_dfrequency, DROP $stg_dorigin, DROP $stg_enddate, DROP  $stg_genddate, DROP $stg_createdBy, DROP $stg_reopened, DROP $stg_last_reopened, DROP $stg_unstarted_notif, DROP $stg_uncompleted_notif, DROP $stg_unfinished_notif, DROP $stg_isFinalized, DROP $stg_deleted, DROP $stg_gcompleted, CHANGE $stg_deadline_mailsent stg_deadline_mail_sent TINYINT(1) DEFAULT NULL, CHANGE $stg_inserted stg_inserted DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_C27C9369E7127ABC ON stage (stg_master_user_id)');
        $this->addSql('ALTER TABLE state DROP FOREIGN KEY FK_A393D2FBA1599B34');
        $this->addSql('ALTER TABLE state DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFC935EEA40');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFCF10DACEE');
        $this->addSql('ALTER TABLE survey DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE survey_field DROP FOREIGN KEY FK_5785B760D26A20E6');
        $this->addSql('ALTER TABLE survey_field DROP FOREIGN KEY FK_5785B7607D7E0D2A');
        $this->addSql('ALTER TABLE survey_field DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE survey_field_parameter DROP FOREIGN KEY FK_6740C5AEAFBE78D8');
        $this->addSql('ALTER TABLE survey_field_parameter DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCF10DACEE');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCB232D839');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCB9E63123');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFC6AFC588');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFC693BC8C6');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFC1C22DDD4');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCCE87AAFC');
        $this->addSql('ALTER TABLE target DROP FOREIGN KEY FK_466F2FFCD26A20E6');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61FF10DACEE');
        $this->addSql('ALTER TABLE team DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C7222321C22DDD4');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C722232693BC8C6');
        $this->addSql('ALTER TABLE team_user DROP FOREIGN KEY FK_5C722232310C5A5A');
        $this->addSql('ALTER TABLE team_user RENAME INDEX idx_5c722232310c5a5a TO IDX_5C722232C258E832');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83935EEA40');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83D26A20E6');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83B232D839');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83F10DACEE');
        $this->addSql('ALTER TABLE template DROP FOREIGN KEY FK_97601F83699ADF0');
        $this->addSql('DROP INDEX IDX_97601F83699ADF0 ON template');
        $this->addSql('ALTER TABLE template DROP createdBy, DROP inserted, CHANGE original_activity_act original_activity_act_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_97601F8341FF5FA2 ON template (original_activity_act_id)');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F3223929F10DACEE');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F3223929B232D839');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F3223929AF5978B5');
        $this->addSql('ALTER TABLE template_activity DROP FOREIGN KEY FK_F32239297083C8AA');
        $this->addSql('DROP INDEX IDX_F32239297083C8AA ON template_activity');
        $this->addSql('ALTER TABLE template_activity DROP act_magnitude, DROP createdBy, DROP inserted, CHANGE act_master_id act_master_usr_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_F32239292267A676 ON template_activity (act_master_usr_id)');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC1C22DDD4');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC83D3BB28');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC935EEA40');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFCD26A20E6');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC693BC8C6');
        $this->addSql('ALTER TABLE template_activity_user DROP FOREIGN KEY FK_951C7CFC310C5A5A');
        $this->addSql('ALTER TABLE template_activity_user CHANGE external_user_ext_usr_id external_user_ext_usr_id INT NOT NULL');
        $this->addSql('ALTER TABLE template_criterion DROP FOREIGN KEY FK_B5D154C7935EEA40');
        $this->addSql('ALTER TABLE template_criterion DROP FOREIGN KEY FK_B5D154C7CE87AAFC');
        $this->addSql('ALTER TABLE template_criterion DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE template_recurring DROP FOREIGN KEY FK_A53F745BF10DACEE');
        $this->addSql('ALTER TABLE template_recurring DROP FOREIGN KEY FK_A53F745B66AC648F');
        $this->addSql('ALTER TABLE template_recurring DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE template_stage DROP FOREIGN KEY FK_F1AA40A683D3BB28');
        $this->addSql('ALTER TABLE template_stage DROP FOREIGN KEY FK_F1AA40A6AFCB9C11');
        $this->addSql('ALTER TABLE template_stage DROP stg_name, DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE title DROP FOREIGN KEY FK_2B36786BF10DACEE');
        $this->addSql('ALTER TABLE title DROP FOREIGN KEY FK_2B36786B3AF408B7');
        $this->addSql('ALTER TABLE title DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B1623D83');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6493AF408B7');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B9E63123');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B232D839');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6496AFC588');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F10DACEE');
        $this->addSql('ALTER TABLE user CHANGE weight_wgt_id weight_wgt_id INT DEFAULT NULL, CHANGE organization_org_id organization_org_id INT DEFAULT NULL, CHANGE usr_picture usr_picture VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE usr_token usr_token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE usr_weight_ini usr_weight_ini DOUBLE PRECISION DEFAULT NULL, CHANGE usr_rm_token usr_rm_token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE usr_validated usr_validated DATETIME DEFAULT NULL, CHANGE usr_enabled_creating_user usr_enabled_creating_user TINYINT(1) DEFAULT NULL, CHANGE usr_created_by usr_created_by INT DEFAULT NULL, CHANGE usr_inserted usr_inserted DATETIME DEFAULT NULL, CHANGE usr_deleted usr_deleted DATETIME DEFAULT NULL, CHANGE usr_superior usr_superior INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user RENAME INDEX idx_8d93d649b232d839 TO IDX_8D93D6493B6FF20A');
        $this->addSql('ALTER TABLE user_tempo CHANGE username username VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE weight DROP FOREIGN KEY FK_7CD5541F4837C1B');
        $this->addSql('ALTER TABLE weight DROP FOREIGN KEY FK_7CD554141085FAE');
        $this->addSql('ALTER TABLE weight DROP FOREIGN KEY FK_7CD5541693BC8C6');
        $this->addSql('DROP INDEX UNIQ_7CD5541693BC8C6 ON weight');
        $this->addSql('ALTER TABLE weight DROP createdBy, DROP inserted, CHANGE user_usr_id user_id INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7CD5541A76ED395 ON weight (user_id)');
        $this->addSql('ALTER TABLE worker_experience DROP FOREIGN KEY FK_81AC8070D4203719');
        $this->addSql('ALTER TABLE worker_experience DROP FOREIGN KEY FK_81AC80708780C6FF');
        $this->addSql('ALTER TABLE worker_experience DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037AC255DBC04');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037AC2391AC72');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037AC2378CB28');
        $this->addSql('ALTER TABLE worker_firm DROP FOREIGN KEY FK_9DC037ACA1599B34');
        $this->addSql('ALTER TABLE worker_firm DROP wfi_creation_date, DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE worker_firm_competency DROP FOREIGN KEY FK_9E94D7EEA8C102B2');
        $this->addSql('ALTER TABLE worker_firm_competency DROP createdBy, DROP inserted');
        $this->addSql('ALTER TABLE worker_firm_sector DROP FOREIGN KEY FK_8DDB61C6E2C46BF8');
    }
}
